/* vocabulary.js — Expanded Vocabulary Data & Set Definitions */
/* ================================================================
   VOCABULARY DATA
================================================================ */

var vocab1 = [
  // === RESTAURANT & DINING ===
  {k:"식당",r:"sikdang",en:"restaurant",pos:"noun"},
  {k:"메뉴",r:"menyu",en:"menu",pos:"noun"},
  {k:"주문",r:"jumun",en:"order",pos:"noun"},
  {k:"계산",r:"gyesan",en:"bill/payment",pos:"noun"},
  {k:"영수증",r:"yeongsujeung",en:"receipt",pos:"noun"},
  {k:"테이블",r:"teibeul",en:"table",pos:"noun"},
  {k:"의자",r:"uija",en:"chair",pos:"noun"},
  {k:"웨이터",r:"weiteo",en:"waiter",pos:"noun"},
  {k:"종업원",r:"jongeopwon",en:"staff/employee",pos:"noun"},
  {k:"사장님",r:"sajangnim",en:"owner/boss",pos:"noun"},
  {k:"예약",r:"yeyak",en:"reservation",pos:"noun"},
  {k:"포장",r:"pojang",en:"takeout/packaging",pos:"noun"},
  {k:"배달",r:"baedal",en:"delivery",pos:"noun"},
  {k:"팁",r:"tip",en:"tip/gratuity",pos:"noun"},
  {k:"반찬",r:"banchan",en:"side dishes",pos:"noun"},
  {k:"국",r:"guk",en:"soup",pos:"noun"},
  {k:"찌개",r:"jjigae",en:"stew",pos:"noun"},
  {k:"밥",r:"bap",en:"rice/meal",pos:"noun"},
  {k:"죽",r:"juk",en:"porridge",pos:"noun"},
  {k:"면",r:"myeon",en:"noodles",pos:"noun"},
  {k:"김치",r:"gimchi",en:"kimchi",pos:"noun"},
  {k:"불고기",r:"bulgogi",en:"bulgogi",pos:"noun"},
  {k:"비빔밥",r:"bibimbap",en:"bibimbap",pos:"noun"},
  {k:"삼겹살",r:"samgyeopsal",en:"pork belly",pos:"noun"},
  {k:"갈비",r:"galbi",en:"ribs",pos:"noun"},
  {k:"된장",r:"doenjang",en:"soybean paste",pos:"noun"},
  {k:"고추장",r:"gochujang",en:"chili paste",pos:"noun"},
  {k:"간장",r:"ganjang",en:"soy sauce",pos:"noun"},
  {k:"참기름",r:"chamgireum",en:"sesame oil",pos:"noun"},
  {k:"식초",r:"sikcho",en:"vinegar",pos:"noun"},
  {k:"설탕",r:"seoltang",en:"sugar",pos:"noun"},
  {k:"소금",r:"sogeum",en:"salt",pos:"noun"},
  {k:"후추",r:"huchu",en:"black pepper",pos:"noun"},
  {k:"마늘",r:"maneul",en:"garlic",pos:"noun"},
  {k:"파",r:"pa",en:"green onion",pos:"noun"},
  {k:"양파",r:"yangpa",en:"onion",pos:"noun"},
  {k:"생강",r:"saenggang",en:"ginger",pos:"noun"},
  {k:"고추",r:"gochu",en:"chili pepper",pos:"noun"},
  {k:"깨",r:"kkae",en:"sesame seeds",pos:"noun"},
  {k:"두부",r:"dubu",en:"tofu",pos:"noun"},
  // KITCHEN TOOLS
  {k:"냄비",r:"naembi",en:"pot",pos:"noun"},
  {k:"프라이팬",r:"peuraipaen",en:"frying pan",pos:"noun"},
  {k:"도마",r:"doma",en:"cutting board",pos:"noun"},
  {k:"칼",r:"kal",en:"knife",pos:"noun"},
  {k:"젓가락",r:"jeotgarak",en:"chopsticks",pos:"noun"},
  {k:"숟가락",r:"sutgarak",en:"spoon",pos:"noun"},
  {k:"포크",r:"pokeu",en:"fork",pos:"noun"},
  {k:"그릇",r:"geureut",en:"bowl/dish",pos:"noun"},
  {k:"컵",r:"keop",en:"cup",pos:"noun"},
  {k:"잔",r:"jan",en:"glass/cup",pos:"noun"},
  {k:"접시",r:"jeopsi",en:"plate",pos:"noun"},
  {k:"냉장고",r:"naengjanggo",en:"refrigerator",pos:"noun"},
  {k:"전자레인지",r:"jeonjareiinji",en:"microwave",pos:"noun"},
  {k:"오븐",r:"obeun",en:"oven",pos:"noun"},
  {k:"가스레인지",r:"gaseureinji",en:"gas stove",pos:"noun"},
  {k:"전기밥솥",r:"jeongibapsot",en:"rice cooker",pos:"noun"},
  {k:"믹서기",r:"mikseogi",en:"blender",pos:"noun"},
  {k:"주전자",r:"jujeonja",en:"kettle",pos:"noun"},
  {k:"행주",r:"haengju",en:"dish towel",pos:"noun"},
  {k:"앞치마",r:"apchima",en:"apron",pos:"noun"},
  // MEAT & SEAFOOD
  {k:"소고기",r:"sogogi",en:"beef",pos:"noun"},
  {k:"돼지고기",r:"dwaejigogi",en:"pork",pos:"noun"},
  {k:"닭고기",r:"dakgogi",en:"chicken",pos:"noun"},
  {k:"생선",r:"saengseon",en:"fish",pos:"noun"},
  {k:"새우",r:"saeu",en:"shrimp",pos:"noun"},
  {k:"조개",r:"jogae",en:"clam",pos:"noun"},
  {k:"오징어",r:"ojingeo",en:"squid",pos:"noun"},
  {k:"게",r:"ge",en:"crab",pos:"noun"},
  {k:"참치",r:"chamchi",en:"tuna",pos:"noun"},
  {k:"연어",r:"yeoneo",en:"salmon",pos:"noun"},
  // VEGETABLES & FRUITS
  {k:"배추",r:"baechu",en:"napa cabbage",pos:"noun"},
  {k:"시금치",r:"sigeumchi",en:"spinach",pos:"noun"},
  {k:"당근",r:"danggeun",en:"carrot",pos:"noun"},
  {k:"감자",r:"gamja",en:"potato",pos:"noun"},
  {k:"고구마",r:"goguma",en:"sweet potato",pos:"noun"},
  {k:"버섯",r:"beoseot",en:"mushroom",pos:"noun"},
  {k:"오이",r:"oi",en:"cucumber",pos:"noun"},
  {k:"토마토",r:"tomato",en:"tomato",pos:"noun"},
  {k:"옥수수",r:"oksusu",en:"corn",pos:"noun"},
  {k:"브로콜리",r:"beurokoli",en:"broccoli",pos:"noun"},
  {k:"사과",r:"sagwa",en:"apple",pos:"noun"},
  {k:"바나나",r:"banana",en:"banana",pos:"noun"},
  {k:"포도",r:"podo",en:"grape",pos:"noun"},
  {k:"딸기",r:"ttalgi",en:"strawberry",pos:"noun"},
  {k:"수박",r:"subak",en:"watermelon",pos:"noun"},
  {k:"복숭아",r:"boksunga",en:"peach",pos:"noun"},
  {k:"귤",r:"gyul",en:"tangerine",pos:"noun"},
  {k:"레몬",r:"remon",en:"lemon",pos:"noun"},
  {k:"망고",r:"manggo",en:"mango",pos:"noun"},
  {k:"배",r:"bae",en:"pear",pos:"noun"},
  // DRINKS & BEVERAGES
  {k:"커피",r:"keopi",en:"coffee",pos:"noun"},
  {k:"녹차",r:"nokcha",en:"green tea",pos:"noun"},
  {k:"홍차",r:"hongcha",en:"black tea",pos:"noun"},
  {k:"주스",r:"juseu",en:"juice",pos:"noun"},
  {k:"우유",r:"uyu",en:"milk",pos:"noun"},
  {k:"맥주",r:"maekju",en:"beer",pos:"noun"},
  {k:"소주",r:"soju",en:"soju",pos:"noun"},
  {k:"막걸리",r:"makgeolli",en:"rice wine",pos:"noun"},
  {k:"와인",r:"wain",en:"wine",pos:"noun"},
  {k:"탄산수",r:"tansansu",en:"sparkling water",pos:"noun"},
  // COOKING INFO
  {k:"요리사",r:"yorisa",en:"chef/cook",pos:"noun"},
  {k:"레시피",r:"resipi",en:"recipe",pos:"noun"},
  {k:"재료",r:"jaeryo",en:"ingredient",pos:"noun"},
  {k:"맛",r:"mat",en:"taste/flavor",pos:"noun"},
  {k:"냄새",r:"naemsae",en:"smell/aroma",pos:"noun"},
  {k:"향",r:"hyang",en:"fragrance/scent",pos:"noun"},
  // COOKING VERBS
  {k:"굽다",r:"gupda",en:"to grill/bake",pos:"verb"},
  {k:"끓이다",r:"kkeuriida",en:"to boil",pos:"verb"},
  {k:"볶다",r:"bokda",en:"to stir-fry",pos:"verb"},
  {k:"튀기다",r:"twigida",en:"to deep-fry",pos:"verb"},
  {k:"찌다",r:"jjida",en:"to steam",pos:"verb"},
  {k:"썰다",r:"sseolda",en:"to slice/chop",pos:"verb"},
  {k:"다지다",r:"dajida",en:"to mince",pos:"verb"},
  {k:"섞다",r:"seokda",en:"to mix",pos:"verb"},
  {k:"붓다",r:"butda",en:"to pour",pos:"verb"},
  {k:"담다",r:"damda",en:"to put in a bowl",pos:"verb"},
  {k:"간하다",r:"ganhada",en:"to season",pos:"verb"},
  {k:"데치다",r:"daechida",en:"to blanch",pos:"verb"},
  {k:"절이다",r:"jeoriida",en:"to pickle/marinate",pos:"verb"},
  {k:"갈다",r:"galda",en:"to grind",pos:"verb"},
  // TASTE ADJECTIVES
  {k:"달다",r:"dalda",en:"sweet",pos:"adj"},
  {k:"짜다",r:"jjada",en:"salty",pos:"adj"},
  {k:"맵다",r:"maepda",en:"spicy",pos:"adj"},
  {k:"시다",r:"sida",en:"sour",pos:"adj"},
  {k:"쓰다",r:"sseuda",en:"bitter",pos:"adj"},
  {k:"싱겁다",r:"singeobda",en:"bland",pos:"adj"},
  {k:"고소하다",r:"gosohada",en:"nutty/savory",pos:"adj"},
  {k:"담백하다",r:"dambaekada",en:"mild/light in taste",pos:"adj"},
  {k:"느끼하다",r:"neukkihada",en:"greasy/rich tasting",pos:"adj"},
  {k:"신선하다",r:"sinseonhada",en:"fresh",pos:"adj"},
  // GRAIN & STAPLES
  {k:"쌀",r:"ssal",en:"uncooked rice",pos:"noun"},
  {k:"밀가루",r:"milgaru",en:"flour",pos:"noun"},
  {k:"빵",r:"ppang",en:"bread",pos:"noun"},
  {k:"떡",r:"tteok",en:"rice cake",pos:"noun"},
  {k:"과자",r:"gwaja",en:"snack/cookie",pos:"noun"},
  {k:"케이크",r:"keikeu",en:"cake",pos:"noun"},
  {k:"아이스크림",r:"aiseukeurim",en:"ice cream",pos:"noun"},
  {k:"사탕",r:"satang",en:"candy",pos:"noun"},
  {k:"초콜릿",r:"chokollit",en:"chocolate",pos:"noun"},
  {k:"라면",r:"ramyeon",en:"instant noodles",pos:"noun"},
  // OILS, DAIRY & EGGS
  {k:"식용유",r:"sigyongyu",en:"cooking oil",pos:"noun"},
  {k:"버터",r:"beoteo",en:"butter",pos:"noun"},
  {k:"치즈",r:"chijeu",en:"cheese",pos:"noun"},
  {k:"요거트",r:"yogeoteu",en:"yogurt",pos:"noun"},
  {k:"달걀",r:"dalgyal",en:"egg",pos:"noun"},
  {k:"흰자",r:"huinja",en:"egg white",pos:"noun"},
  {k:"노른자",r:"noreunjja",en:"egg yolk",pos:"noun"},
  {k:"생크림",r:"saengkeurim",en:"heavy cream",pos:"noun"},
  {k:"두유",r:"duyu",en:"soy milk",pos:"noun"},
  {k:"꿀",r:"kkul",en:"honey",pos:"noun"},
  // RESTAURANT VERBS
  {k:"주문하다",r:"jumunhada",en:"to order",pos:"verb"},
  {k:"예약하다",r:"yeyakhada",en:"to make a reservation",pos:"verb"},
  {k:"계산하다",r:"gyesanhada",en:"to pay the bill",pos:"verb"},
  {k:"포장하다",r:"pojanghada",en:"to pack up/wrap",pos:"verb"},
  {k:"배달하다",r:"baedalhada",en:"to deliver",pos:"verb"},
  {k:"추천하다",r:"chucheonhada",en:"to recommend",pos:"verb"},
  {k:"맛보다",r:"matboda",en:"to taste/try food",pos:"verb"},
  {k:"남기다",r:"namgida",en:"to leave behind/leftovers",pos:"verb"},
  {k:"나누다",r:"nanuda",en:"to share/split",pos:"verb"},
  {k:"시키다",r:"sikida",en:"to order/have someone do",pos:"verb"},
  // DINING PHRASES
  {k:"맛있게 드세요",r:"masitge deuseyo",en:"enjoy your meal",pos:"phrase"},
  {k:"잘 먹겠습니다",r:"jal meokgesseumnida",en:"I will eat well (before eating)",pos:"phrase"},
  {k:"잘 먹었습니다",r:"jal meogeosseumnida",en:"I ate well (after eating)",pos:"phrase"},
  {k:"한 잔 더",r:"han jan deo",en:"one more glass",pos:"phrase"},
  {k:"한 그릇 더",r:"han geureut deo",en:"one more bowl",pos:"phrase"},
  {k:"얼마예요",r:"eolmayeyo",en:"how much is it",pos:"phrase"},
  {k:"따로따로",r:"ttarottaro",en:"separately (split bill)",pos:"phrase"},
  {k:"같이 내다",r:"gachi naeda",en:"to pay together",pos:"phrase"},
  {k:"서비스",r:"seobiseu",en:"complimentary/service",pos:"noun"},
  {k:"회식",r:"hoesik",en:"company dinner",pos:"noun"},
  // KITCHEN EXTRAS
  {k:"냄비받침",r:"naembibatchim",en:"pot holder/trivet",pos:"noun"},
  {k:"거품기",r:"geoumgi",en:"whisk",pos:"noun"},
  {k:"체",r:"che",en:"strainer/sieve",pos:"noun"},
  {k:"뒤집개",r:"dwijijkkae",en:"spatula/flipper",pos:"noun"},
  {k:"국자",r:"gukja",en:"ladle",pos:"noun"},
  {k:"집게",r:"jipge",en:"tongs",pos:"noun"},
  {k:"병따개",r:"byeongttakae",en:"bottle opener",pos:"noun"},
  {k:"깡통따개",r:"kkangtongtakae",en:"can opener",pos:"noun"},
  {k:"랩",r:"raep",en:"plastic wrap",pos:"noun"},
  {k:"호일",r:"hoil",en:"foil",pos:"noun"},
  // COOKING CONDITIONS
  {k:"약불",r:"yakbul",en:"low heat",pos:"noun"},
  {k:"강불",r:"gangbul",en:"high heat",pos:"noun"},
  {k:"중불",r:"jungbul",en:"medium heat",pos:"noun"},
  {k:"온도",r:"ondo",en:"temperature",pos:"noun"},
  {k:"양",r:"yang",en:"amount/quantity",pos:"noun"},
  {k:"한 컵",r:"han keop",en:"one cup",pos:"phrase"},
  {k:"한 큰술",r:"han keunssul",en:"one tablespoon",pos:"phrase"},
  {k:"한 작은술",r:"han jageunssul",en:"one teaspoon",pos:"phrase"},
  {k:"한 꼬집",r:"han kkojip",en:"a pinch (of)",pos:"phrase"},
  // TASTE & QUALITY
  {k:"맛없다",r:"maseobda",en:"tasteless/bad tasting",pos:"adj"},
  {k:"뜨겁다",r:"tteugeopda",en:"hot (temperature)",pos:"adj"},
  {k:"차갑다",r:"chagapda",en:"cold (temperature)",pos:"adj"},
  {k:"익다",r:"ikda",en:"to be cooked/ripe",pos:"verb"},
  {k:"타다",r:"tada",en:"to burn/char",pos:"verb"},
  {k:"식다",r:"sikda",en:"to cool down",pos:"verb"},
  {k:"굳다",r:"gutda",en:"to harden/solidify",pos:"verb"},
  {k:"녹다",r:"nokda",en:"to melt",pos:"verb"},
  {k:"끓다",r:"kkeulda",en:"to boil",pos:"verb"},
  {k:"졸이다",r:"joriida",en:"to reduce (liquid)",pos:"verb"},
];

var vocab2 = [
  // NATURE & LANDSCAPE
  {k:"산",r:"san",en:"mountain",pos:"noun"},
  {k:"강",r:"gang",en:"river",pos:"noun"},
  {k:"바다",r:"bada",en:"sea/ocean",pos:"noun"},
  {k:"호수",r:"hosu",en:"lake",pos:"noun"},
  {k:"섬",r:"seom",en:"island",pos:"noun"},
  {k:"숲",r:"sup",en:"forest",pos:"noun"},
  {k:"들판",r:"deulpan",en:"field/plain",pos:"noun"},
  {k:"사막",r:"samak",en:"desert",pos:"noun"},
  {k:"폭포",r:"pokpo",en:"waterfall",pos:"noun"},
  {k:"동굴",r:"donggul",en:"cave",pos:"noun"},
  {k:"절벽",r:"jeolbyeok",en:"cliff",pos:"noun"},
  {k:"언덕",r:"eondeok",en:"hill",pos:"noun"},
  {k:"계곡",r:"gyegok",en:"valley/gorge",pos:"noun"},
  {k:"해변",r:"haebyeon",en:"beach",pos:"noun"},
  {k:"갯벌",r:"gaetbeol",en:"tidal flat",pos:"noun"},
  {k:"늪",r:"neup",en:"swamp/marsh",pos:"noun"},
  {k:"초원",r:"chowon",en:"grassland/meadow",pos:"noun"},
  {k:"화산",r:"hwasan",en:"volcano",pos:"noun"},
  {k:"빙하",r:"bingha",en:"glacier",pos:"noun"},
  {k:"지평선",r:"jipyeongseon",en:"horizon",pos:"noun"},
  // WEATHER
  {k:"구름",r:"gureum",en:"cloud",pos:"noun"},
  {k:"비",r:"bi",en:"rain",pos:"noun"},
  {k:"눈",r:"nun",en:"snow",pos:"noun"},
  {k:"바람",r:"baram",en:"wind",pos:"noun"},
  {k:"안개",r:"angae",en:"fog/mist",pos:"noun"},
  {k:"천둥",r:"cheondung",en:"thunder",pos:"noun"},
  {k:"번개",r:"beongae",en:"lightning",pos:"noun"},
  {k:"태풍",r:"taepung",en:"typhoon",pos:"noun"},
  {k:"홍수",r:"hongsu",en:"flood",pos:"noun"},
  {k:"가뭄",r:"gamum",en:"drought",pos:"noun"},
  {k:"지진",r:"jijin",en:"earthquake",pos:"noun"},
  {k:"폭설",r:"pokseol",en:"heavy snow",pos:"noun"},
  {k:"황사",r:"hwangsa",en:"yellow dust/sandstorm",pos:"noun"},
  {k:"무지개",r:"mujigae",en:"rainbow",pos:"noun"},
  {k:"서리",r:"seori",en:"frost",pos:"noun"},
  {k:"우박",r:"ubak",en:"hail",pos:"noun"},
  {k:"이슬",r:"iseul",en:"dew",pos:"noun"},
  {k:"습도",r:"supdo",en:"humidity",pos:"noun"},
  {k:"기온",r:"gion",en:"air temperature",pos:"noun"},
  {k:"기압",r:"giap",en:"air pressure",pos:"noun"},
  // ANIMALS
  {k:"강아지",r:"gangaji",en:"puppy/dog",pos:"noun"},
  {k:"고양이",r:"goyangi",en:"cat",pos:"noun"},
  {k:"새",r:"sae",en:"bird",pos:"noun"},
  {k:"물고기",r:"mulgogi",en:"fish (general)",pos:"noun"},
  {k:"토끼",r:"tokki",en:"rabbit",pos:"noun"},
  {k:"곰",r:"gom",en:"bear",pos:"noun"},
  {k:"호랑이",r:"horangi",en:"tiger",pos:"noun"},
  {k:"사자",r:"saja",en:"lion",pos:"noun"},
  {k:"코끼리",r:"kokkiri",en:"elephant",pos:"noun"},
  {k:"기린",r:"girin",en:"giraffe",pos:"noun"},
  {k:"원숭이",r:"wonsungi",en:"monkey",pos:"noun"},
  {k:"늑대",r:"neukdae",en:"wolf",pos:"noun"},
  {k:"여우",r:"yeou",en:"fox",pos:"noun"},
  {k:"사슴",r:"saseum",en:"deer",pos:"noun"},
  {k:"뱀",r:"baem",en:"snake",pos:"noun"},
  {k:"개구리",r:"gaeguri",en:"frog",pos:"noun"},
  {k:"나비",r:"nabi",en:"butterfly",pos:"noun"},
  {k:"벌",r:"beol",en:"bee",pos:"noun"},
  {k:"개미",r:"gaemi",en:"ant",pos:"noun"},
  {k:"모기",r:"mogi",en:"mosquito",pos:"noun"},
  // PLANTS
  {k:"나무",r:"namu",en:"tree",pos:"noun"},
  {k:"꽃",r:"kkot",en:"flower",pos:"noun"},
  {k:"풀",r:"pul",en:"grass/weed",pos:"noun"},
  {k:"나뭇잎",r:"namu-ip",en:"leaf",pos:"noun"},
  {k:"뿌리",r:"ppuri",en:"root",pos:"noun"},
  {k:"줄기",r:"julgi",en:"stem/trunk",pos:"noun"},
  {k:"가지",r:"gaji",en:"branch",pos:"noun"},
  {k:"씨앗",r:"ssi-at",en:"seed",pos:"noun"},
  {k:"솔잎",r:"sol-ip",en:"pine needle",pos:"noun"},
  {k:"선인장",r:"seonjnjang",en:"cactus",pos:"noun"},
  // SCIENCE & TECHNOLOGY
  {k:"과학",r:"gwahak",en:"science",pos:"noun"},
  {k:"기술",r:"gisul",en:"technology",pos:"noun"},
  {k:"컴퓨터",r:"keompyuteo",en:"computer",pos:"noun"},
  {k:"스마트폰",r:"seumateupon",en:"smartphone",pos:"noun"},
  {k:"인터넷",r:"inteonet",en:"internet",pos:"noun"},
  {k:"소프트웨어",r:"sopeuteuweeo",en:"software",pos:"noun"},
  {k:"앱",r:"aep",en:"app",pos:"noun"},
  {k:"데이터",r:"deiteo",en:"data",pos:"noun"},
  {k:"네트워크",r:"neteuwokeu",en:"network",pos:"noun"},
  {k:"인공지능",r:"ingongjineung",en:"artificial intelligence",pos:"noun"},
  {k:"로봇",r:"robot",en:"robot",pos:"noun"},
  {k:"드론",r:"deuron",en:"drone",pos:"noun"},
  {k:"카메라",r:"kamaera",en:"camera",pos:"noun"},
  {k:"배터리",r:"baeteori",en:"battery",pos:"noun"},
  {k:"충전기",r:"chungjeongi",en:"charger",pos:"noun"},
  {k:"화면",r:"hwamyeon",en:"screen/display",pos:"noun"},
  {k:"키보드",r:"kibodeu",en:"keyboard",pos:"noun"},
  {k:"마우스",r:"mauseu",en:"mouse (computer)",pos:"noun"},
  {k:"프린터",r:"peurinteo",en:"printer",pos:"noun"},
  {k:"스피커",r:"seupikeo",en:"speaker",pos:"noun"},
  // ENVIRONMENT
  {k:"환경",r:"hwangyeong",en:"environment",pos:"noun"},
  {k:"오염",r:"oyeom",en:"pollution",pos:"noun"},
  {k:"재활용",r:"jaehwalyong",en:"recycling",pos:"noun"},
  {k:"에너지",r:"eneoji",en:"energy",pos:"noun"},
  {k:"태양에너지",r:"taeyang-eneoji",en:"solar energy",pos:"noun"},
  {k:"탄소",r:"tanso",en:"carbon",pos:"noun"},
  {k:"온실가스",r:"onsilgaseu",en:"greenhouse gas",pos:"noun"},
  {k:"지구온난화",r:"jigu-onnanwa",en:"global warming",pos:"noun"},
  {k:"생태계",r:"saengtaegye",en:"ecosystem",pos:"noun"},
  {k:"멸종",r:"myeoljong",en:"extinction",pos:"noun"},
  // SPACE
  {k:"우주",r:"uju",en:"universe/space",pos:"noun"},
  {k:"별",r:"byeol",en:"star",pos:"noun"},
  {k:"달",r:"dal",en:"moon",pos:"noun"},
  {k:"태양",r:"taeyang",en:"sun",pos:"noun"},
  {k:"행성",r:"haengseong",en:"planet",pos:"noun"},
  {k:"혜성",r:"hyeseong",en:"comet",pos:"noun"},
  {k:"은하",r:"eunha",en:"galaxy",pos:"noun"},
  {k:"블랙홀",r:"beullaekol",en:"black hole",pos:"noun"},
  {k:"로켓",r:"roket",en:"rocket",pos:"noun"},
  {k:"위성",r:"wiseong",en:"satellite",pos:"noun"},
  // SCIENCE VERBS
  {k:"연구하다",r:"yeonguhada",en:"to research",pos:"verb"},
  {k:"실험하다",r:"silheomhada",en:"to experiment",pos:"verb"},
  {k:"발견하다",r:"balgyeonhada",en:"to discover",pos:"verb"},
  {k:"발명하다",r:"balmyeonghada",en:"to invent",pos:"verb"},
  {k:"측정하다",r:"cheukjeonghada",en:"to measure",pos:"verb"},
  {k:"분석하다",r:"bunseokhada",en:"to analyze",pos:"verb"},
  {k:"관찰하다",r:"gwanchalhada",en:"to observe",pos:"verb"},
  {k:"계산하다",r:"gyesanhada",en:"to calculate",pos:"verb"},
  {k:"설계하다",r:"seolgyehada",en:"to design/plan",pos:"verb"},
  {k:"개발하다",r:"gaebalhada",en:"to develop",pos:"verb"},
  // TECH VERBS
  {k:"검색하다",r:"geomsaekada",en:"to search",pos:"verb"},
  {k:"다운로드하다",r:"daunrodeu-hada",en:"to download",pos:"verb"},
  {k:"업로드하다",r:"eomrodeu-hada",en:"to upload",pos:"verb"},
  {k:"저장하다",r:"jeojanghada",en:"to save/store",pos:"verb"},
  {k:"삭제하다",r:"sakjehada",en:"to delete",pos:"verb"},
  {k:"설치하다",r:"seolchihada",en:"to install",pos:"verb"},
  {k:"업데이트하다",r:"eopdeiteu-hada",en:"to update",pos:"verb"},
  {k:"연결하다",r:"yeongyeolhada",en:"to connect",pos:"verb"},
  {k:"공유하다",r:"gongyuhada",en:"to share",pos:"verb"},
  {k:"전송하다",r:"jeonssonghada",en:"to send/transmit",pos:"verb"},
  // NATURE ADJECTIVES
  {k:"깊다",r:"gipda",en:"deep",pos:"adj"},
  {k:"얕다",r:"yaetda",en:"shallow",pos:"adj"},
  {k:"거칠다",r:"geochilda",en:"rough/coarse",pos:"adj"},
  {k:"부드럽다",r:"budeureopda",en:"soft/smooth",pos:"adj"},
  {k:"맑다",r:"makda",en:"clear/clear sky",pos:"adj"},
  {k:"흐리다",r:"heurida",en:"cloudy/overcast",pos:"adj"},
  {k:"습하다",r:"suphada",en:"humid/damp",pos:"adj"},
  {k:"건조하다",r:"geonnhada",en:"dry",pos:"adj"},
  {k:"뜨겁다",r:"tteugeopda",en:"hot to the touch",pos:"adj"},
  {k:"차다",r:"chada",en:"cold/chilly",pos:"adj"},
  // SCIENCE TERMS
  {k:"정확하다",r:"jeonghwakhada",en:"accurate/precise",pos:"adj"},
  {k:"복잡하다",r:"bokjaphada",en:"complex/complicated",pos:"adj"},
  {k:"단순하다",r:"dansunhada",en:"simple",pos:"adj"},
  {k:"효율적이다",r:"hyoyuljeogida",en:"efficient",pos:"adj"},
  {k:"디지털",r:"dijiteol",en:"digital",pos:"noun"},
  {k:"아날로그",r:"anallogu",en:"analog",pos:"noun"},
  {k:"무선",r:"museon",en:"wireless",pos:"noun"},
  {k:"유선",r:"yuseon",en:"wired",pos:"noun"},
  {k:"전파",r:"jeonpa",en:"radio wave",pos:"noun"},
  // SEASONS & TIME
  {k:"봄",r:"bom",en:"spring",pos:"noun"},
  {k:"여름",r:"yeoreum",en:"summer",pos:"noun"},
  {k:"가을",r:"gaeul",en:"autumn/fall",pos:"noun"},
  {k:"겨울",r:"gyeoul",en:"winter",pos:"noun"},
  {k:"일출",r:"ilchul",en:"sunrise",pos:"noun"},
  {k:"일몰",r:"ilmol",en:"sunset",pos:"noun"},
  {k:"새벽",r:"saebyeok",en:"dawn",pos:"noun"},
  {k:"황혼",r:"hwanghon",en:"dusk/twilight",pos:"noun"},
  {k:"만조",r:"manjo",en:"high tide",pos:"noun"},
  {k:"간조",r:"ganjo",en:"low tide",pos:"noun"},
  // MATERIALS
  {k:"돌",r:"dol",en:"stone/rock",pos:"noun"},
  {k:"흙",r:"heuk",en:"soil/earth/dirt",pos:"noun"},
  {k:"모래",r:"morae",en:"sand",pos:"noun"},
  {k:"얼음",r:"eoreum",en:"ice",pos:"noun"},
  {k:"증기",r:"jeunggi",en:"steam/vapor",pos:"noun"},
  {k:"공기",r:"gonggi",en:"air",pos:"noun"},
  {k:"산소",r:"sanso",en:"oxygen",pos:"noun"},
  {k:"수소",r:"suso",en:"hydrogen",pos:"noun"},
  {k:"금속",r:"geumsok",en:"metal",pos:"noun"},
  {k:"플라스틱",r:"peullaseutik",en:"plastic",pos:"noun"},
];

var vocab3 = [
  // EDUCATION
  {k:"교육",r:"gyoyuk",en:"education",pos:"noun"},
  {k:"대학교",r:"daehakgyo",en:"university",pos:"noun"},
  {k:"고등학교",r:"godeunghakgyo",en:"high school",pos:"noun"},
  {k:"중학교",r:"junghakgyo",en:"middle school",pos:"noun"},
  {k:"초등학교",r:"chodeunghakgyo",en:"elementary school",pos:"noun"},
  {k:"유치원",r:"yuchiwon",en:"kindergarten",pos:"noun"},
  {k:"교실",r:"gyosil",en:"classroom",pos:"noun"},
  {k:"강의실",r:"gangyusil",en:"lecture room",pos:"noun"},
  {k:"도서관",r:"doseogwan",en:"library",pos:"noun"},
  {k:"책",r:"chaek",en:"book",pos:"noun"},
  {k:"교과서",r:"gyogwaseo",en:"textbook",pos:"noun"},
  {k:"공책",r:"gongchaek",en:"notebook",pos:"noun"},
  {k:"연필",r:"yeonpil",en:"pencil",pos:"noun"},
  {k:"볼펜",r:"bolpen",en:"ballpoint pen",pos:"noun"},
  {k:"지우개",r:"jiugae",en:"eraser",pos:"noun"},
  {k:"자",r:"ja",en:"ruler",pos:"noun"},
  {k:"시험",r:"siheom",en:"exam/test",pos:"noun"},
  {k:"성적",r:"seongjeok",en:"grade/score",pos:"noun"},
  {k:"숙제",r:"sukje",en:"homework",pos:"noun"},
  {k:"과제",r:"gwaje",en:"assignment/project",pos:"noun"},
  {k:"졸업",r:"joreoep",en:"graduation",pos:"noun"},
  {k:"입학",r:"iphak",en:"enrollment/admission",pos:"noun"},
  {k:"장학금",r:"janghakgeum",en:"scholarship",pos:"noun"},
  {k:"전공",r:"jeongong",en:"major (academic)",pos:"noun"},
  {k:"수업",r:"sueop",en:"class/lesson",pos:"noun"},
  // WORK & CAREER
  {k:"직업",r:"jigeop",en:"job/occupation",pos:"noun"},
  {k:"직원",r:"jigwon",en:"employee",pos:"noun"},
  {k:"상사",r:"sangsa",en:"boss/superior",pos:"noun"},
  {k:"부하",r:"buha",en:"subordinate",pos:"noun"},
  {k:"팀",r:"tim",en:"team",pos:"noun"},
  {k:"부서",r:"buseo",en:"department",pos:"noun"},
  {k:"사무실",r:"samusil",en:"office",pos:"noun"},
  {k:"회의",r:"hoeui",en:"meeting",pos:"noun"},
  {k:"보고서",r:"bogoseo",en:"report",pos:"noun"},
  {k:"서류",r:"seoryu",en:"document/paperwork",pos:"noun"},
  {k:"계약",r:"gyeyak",en:"contract",pos:"noun"},
  {k:"급여",r:"geubyeo",en:"salary/pay",pos:"noun"},
  {k:"월급",r:"wolgup",en:"monthly salary",pos:"noun"},
  {k:"세금",r:"segeum",en:"tax",pos:"noun"},
  {k:"연봉",r:"yeonbong",en:"annual salary",pos:"noun"},
  {k:"출퇴근",r:"chultoegen",en:"commute",pos:"noun"},
  {k:"야근",r:"yageun",en:"overtime work",pos:"noun"},
  {k:"휴가",r:"hyuga",en:"vacation/leave",pos:"noun"},
  {k:"이직",r:"ijik",en:"job change",pos:"noun"},
  {k:"취업",r:"chwieop",en:"getting a job",pos:"noun"},
  {k:"실업",r:"sireop",en:"unemployment",pos:"noun"},
  {k:"인턴",r:"inteon",en:"intern",pos:"noun"},
  {k:"프리랜서",r:"peurilaenseo",en:"freelancer",pos:"noun"},
  {k:"면접",r:"myeonjeop",en:"interview",pos:"noun"},
  {k:"이력서",r:"iryeokseo",en:"resume/CV",pos:"noun"},
  // HEALTH & BODY
  {k:"건강",r:"geongang",en:"health",pos:"noun"},
  {k:"질병",r:"jilbyeong",en:"disease/illness",pos:"noun"},
  {k:"감기",r:"gamgi",en:"cold (illness)",pos:"noun"},
  {k:"독감",r:"dokgam",en:"flu/influenza",pos:"noun"},
  {k:"열",r:"yeol",en:"fever",pos:"noun"},
  {k:"기침",r:"gichim",en:"cough",pos:"noun"},
  {k:"두통",r:"dutong",en:"headache",pos:"noun"},
  {k:"복통",r:"boktong",en:"stomachache",pos:"noun"},
  {k:"알레르기",r:"allereugi",en:"allergy",pos:"noun"},
  {k:"상처",r:"sangcheo",en:"wound/injury",pos:"noun"},
  {k:"수술",r:"susul",en:"surgery/operation",pos:"noun"},
  {k:"입원",r:"ibwon",en:"hospitalization",pos:"noun"},
  {k:"퇴원",r:"toewon",en:"discharge from hospital",pos:"noun"},
  {k:"처방",r:"cheobang",en:"prescription",pos:"noun"},
  {k:"약",r:"yak",en:"medicine",pos:"noun"},
  {k:"주사",r:"jusa",en:"injection/shot",pos:"noun"},
  {k:"혈액",r:"hyeolaek",en:"blood",pos:"noun"},
  {k:"혈압",r:"hyeorap",en:"blood pressure",pos:"noun"},
  {k:"체온",r:"cheon",en:"body temperature",pos:"noun"},
  {k:"맥박",r:"maekbak",en:"pulse",pos:"noun"},
  {k:"의사",r:"uisa",en:"doctor",pos:"noun"},
  {k:"간호사",r:"ganhosa",en:"nurse",pos:"noun"},
  {k:"치과",r:"chigwa",en:"dentist/dental clinic",pos:"noun"},
  {k:"안과",r:"angwa",en:"ophthalmologist",pos:"noun"},
  {k:"정형외과",r:"jeonghyeong-oegwa",en:"orthopedic clinic",pos:"noun"},
  // HEALTH VERBS
  {k:"진찰하다",r:"jinchalhada",en:"to examine (medical)",pos:"verb"},
  {k:"치료하다",r:"chiryohada",en:"to treat medically",pos:"verb"},
  {k:"회복하다",r:"hoeBokhada",en:"to recover",pos:"verb"},
  {k:"예방하다",r:"yebbanghada",en:"to prevent",pos:"verb"},
  {k:"운동하다",r:"undonghada",en:"to exercise",pos:"verb"},
  {k:"쉬다",r:"swida",en:"to rest",pos:"verb"},
  {k:"숨쉬다",r:"sumswida",en:"to breathe",pos:"verb"},
  {k:"다치다",r:"dachida",en:"to get hurt",pos:"verb"},
  {k:"낫다",r:"natda",en:"to get better/heal",pos:"verb"},
  // SOCIETY
  {k:"사회",r:"sahoe",en:"society",pos:"noun"},
  {k:"정부",r:"jeonbu",en:"government",pos:"noun"},
  {k:"법",r:"beop",en:"law",pos:"noun"},
  {k:"규칙",r:"gyuchik",en:"rule/regulation",pos:"noun"},
  {k:"권리",r:"gwonli",en:"right/rights",pos:"noun"},
  {k:"의무",r:"uimu",en:"duty/obligation",pos:"noun"},
  {k:"선거",r:"seongeeo",en:"election",pos:"noun"},
  {k:"투표",r:"tupyo",en:"voting/ballot",pos:"noun"},
  {k:"경찰",r:"gyeongchal",en:"police",pos:"noun"},
  {k:"군인",r:"gunin",en:"soldier",pos:"noun"},
  {k:"소방관",r:"sobanggwan",en:"firefighter",pos:"noun"},
  {k:"판사",r:"pansa",en:"judge",pos:"noun"},
  {k:"변호사",r:"byeonhosa",en:"lawyer",pos:"noun"},
  {k:"국회",r:"gukhoe",en:"national assembly",pos:"noun"},
  {k:"대통령",r:"daetongryeong",en:"president (of a country)",pos:"noun"},
  {k:"시장",r:"sijang",en:"mayor",pos:"noun"},
  {k:"세계",r:"segye",en:"world",pos:"noun"},
  {k:"국가",r:"gukga",en:"nation/state",pos:"noun"},
  {k:"외국",r:"oeguk",en:"foreign country",pos:"noun"},
  {k:"문화",r:"munhwa",en:"culture",pos:"noun"},
  // WORK VERBS
  {k:"지원하다",r:"jiwonhada",en:"to apply for a job",pos:"verb"},
  {k:"채용하다",r:"chaeyonghada",en:"to hire",pos:"verb"},
  {k:"해고하다",r:"haegohada",en:"to fire/dismiss",pos:"verb"},
  {k:"출근하다",r:"chulgeunhada",en:"to go to work",pos:"verb"},
  {k:"퇴근하다",r:"toegeunhada",en:"to leave work",pos:"verb"},
  {k:"근무하다",r:"geunmuhada",en:"to work/be on duty",pos:"verb"},
  {k:"협력하다",r:"hyeomnyeokhada",en:"to cooperate",pos:"verb"},
  {k:"보고하다",r:"bogohada",en:"to report",pos:"verb"},
  {k:"승진하다",r:"seungjinhada",en:"to get promoted",pos:"verb"},
  {k:"사직하다",r:"sajikada",en:"to resign",pos:"verb"},
  // FINANCE
  {k:"경제",r:"gyeongje",en:"economy",pos:"noun"},
  {k:"돈",r:"don",en:"money",pos:"noun"},
  {k:"은행",r:"eunhaeng",en:"bank",pos:"noun"},
  {k:"계좌",r:"gyejwa",en:"bank account",pos:"noun"},
  {k:"카드",r:"kadeu",en:"card (credit/debit)",pos:"noun"},
  {k:"현금",r:"hyeongeum",en:"cash",pos:"noun"},
  {k:"환율",r:"hwanyul",en:"exchange rate",pos:"noun"},
  {k:"투자",r:"tuja",en:"investment",pos:"noun"},
  {k:"주식",r:"jusik",en:"stock/shares",pos:"noun"},
  {k:"부동산",r:"budongsan",en:"real estate",pos:"noun"},
  {k:"대출",r:"daechul",en:"loan",pos:"noun"},
  {k:"예금",r:"yegeum",en:"savings/deposit",pos:"noun"},
  {k:"이자",r:"ija",en:"interest (financial)",pos:"noun"},
  {k:"물가",r:"mulga",en:"price level/cost of living",pos:"noun"},
  {k:"소비",r:"sobi",en:"consumption/spending",pos:"noun"},
  // ADJECTIVES
  {k:"중요하다",r:"jungyohada",en:"important",pos:"adj"},
  {k:"필요하다",r:"piryohada",en:"necessary",pos:"adj"},
  {k:"가능하다",r:"ganeunghada",en:"possible",pos:"adj"},
  {k:"불가능하다",r:"bulganeunghada",en:"impossible",pos:"adj"},
  {k:"어렵다",r:"eoryeopda",en:"difficult",pos:"adj"},
  {k:"쉽다",r:"swipda",en:"easy",pos:"adj"},
  {k:"안전하다",r:"anjeonhada",en:"safe",pos:"adj"},
  {k:"위험하다",r:"wiheomhada",en:"dangerous",pos:"adj"},
  {k:"유명하다",r:"yumyeonghada",en:"famous",pos:"adj"},
  {k:"성공적이다",r:"seonggongjeogida",en:"successful",pos:"adj"},
  // PHRASES
  {k:"수고하셨습니다",r:"sugohasyeosseumnida",en:"you've worked hard (respectful)",pos:"phrase"},
  {k:"화이팅",r:"hwaiting",en:"fighting!/you can do it!",pos:"phrase"},
  {k:"잘 부탁드립니다",r:"jal butakdeurimnida",en:"please take care of me",pos:"phrase"},
  {k:"감사합니다",r:"gamsahamnida",en:"thank you (formal)",pos:"phrase"},
  {k:"죄송합니다",r:"joesonghamnida",en:"I am sorry (formal)",pos:"phrase"},
  {k:"괜찮으세요",r:"gwaenchaneuseyo",en:"are you alright?",pos:"phrase"},
  {k:"건강 조심하세요",r:"geongang josimhaseyo",en:"take care of your health",pos:"phrase"},
  {k:"빨리 나으세요",r:"ppalli naeseyo",en:"get well soon",pos:"phrase"},
  {k:"열심히 하세요",r:"yeolsimhi haseyo",en:"do your best/work hard",pos:"phrase"},
  {k:"좋은 하루 되세요",r:"joeun haru doeseyo",en:"have a good day",pos:"phrase"},
];

var vocab4 = [
  // ARTS & CULTURE
  {k:"예술",r:"yesul",en:"art",pos:"noun"},
  {k:"음악",r:"eumak",en:"music",pos:"noun"},
  {k:"미술",r:"misul",en:"fine art/painting",pos:"noun"},
  {k:"춤",r:"chum",en:"dance",pos:"noun"},
  {k:"노래",r:"norae",en:"song",pos:"noun"},
  {k:"악기",r:"akgi",en:"musical instrument",pos:"noun"},
  {k:"기타",r:"gita",en:"guitar",pos:"noun"},
  {k:"피아노",r:"piano",en:"piano",pos:"noun"},
  {k:"바이올린",r:"baiorin",en:"violin",pos:"noun"},
  {k:"드럼",r:"deureum",en:"drums",pos:"noun"},
  {k:"영화",r:"yeonghwa",en:"movie/film",pos:"noun"},
  {k:"드라마",r:"deurama",en:"TV drama/series",pos:"noun"},
  {k:"연극",r:"yeongeuk",en:"play/theater",pos:"noun"},
  {k:"공연",r:"gongyeon",en:"performance/show",pos:"noun"},
  {k:"전시회",r:"jeonsihoe",en:"exhibition",pos:"noun"},
  {k:"박물관",r:"bangmulgwan",en:"museum",pos:"noun"},
  {k:"미술관",r:"misulgwan",en:"art gallery",pos:"noun"},
  {k:"극장",r:"geukjang",en:"theater/cinema",pos:"noun"},
  {k:"콘서트",r:"konseoteu",en:"concert",pos:"noun"},
  {k:"축제",r:"chukje",en:"festival",pos:"noun"},
  {k:"소설",r:"soseol",en:"novel",pos:"noun"},
  {k:"시",r:"si",en:"poetry",pos:"noun"},
  {k:"만화",r:"manhwa",en:"comic/cartoon",pos:"noun"},
  {k:"사진",r:"sajin",en:"photo/photography",pos:"noun"},
  {k:"그림",r:"geurim",en:"picture/painting",pos:"noun"},
  // SPORTS
  {k:"스포츠",r:"seupocheu",en:"sports",pos:"noun"},
  {k:"축구",r:"chukgu",en:"soccer/football",pos:"noun"},
  {k:"야구",r:"yagu",en:"baseball",pos:"noun"},
  {k:"농구",r:"nonggu",en:"basketball",pos:"noun"},
  {k:"배구",r:"baegu",en:"volleyball",pos:"noun"},
  {k:"테니스",r:"teniseu",en:"tennis",pos:"noun"},
  {k:"수영",r:"suyeong",en:"swimming",pos:"noun"},
  {k:"달리기",r:"dalligi",en:"running",pos:"noun"},
  {k:"등산",r:"deungsan",en:"hiking",pos:"noun"},
  {k:"자전거",r:"jajeongeo",en:"bicycle",pos:"noun"},
  {k:"태권도",r:"taegwondo",en:"taekwondo",pos:"noun"},
  {k:"유도",r:"yudo",en:"judo",pos:"noun"},
  {k:"골프",r:"golpeu",en:"golf",pos:"noun"},
  {k:"스키",r:"seuki",en:"skiing",pos:"noun"},
  {k:"팀원",r:"timwon",en:"team member",pos:"noun"},
  {k:"심판",r:"simpan",en:"referee/umpire",pos:"noun"},
  {k:"경기",r:"gyeonggi",en:"game/match",pos:"noun"},
  {k:"점수",r:"jeomssu",en:"score/points",pos:"noun"},
  {k:"우승",r:"useung",en:"championship/first place",pos:"noun"},
  {k:"패배",r:"paebae",en:"defeat/loss",pos:"noun"},
  // HOME & FURNITURE
  {k:"집",r:"jip",en:"house/home",pos:"noun"},
  {k:"아파트",r:"apateu",en:"apartment",pos:"noun"},
  {k:"방",r:"bang",en:"room",pos:"noun"},
  {k:"거실",r:"geosil",en:"living room",pos:"noun"},
  {k:"침실",r:"chimsil",en:"bedroom",pos:"noun"},
  {k:"주방",r:"jubang",en:"kitchen",pos:"noun"},
  {k:"화장실",r:"hwajangshil",en:"bathroom/restroom",pos:"noun"},
  {k:"욕실",r:"yoksil",en:"bathroom (with tub)",pos:"noun"},
  {k:"복도",r:"bokdo",en:"hallway/corridor",pos:"noun"},
  {k:"계단",r:"gyedan",en:"stairs",pos:"noun"},
  {k:"엘리베이터",r:"elribeeiteo",en:"elevator",pos:"noun"},
  {k:"지붕",r:"jibung",en:"roof",pos:"noun"},
  {k:"벽",r:"byeok",en:"wall",pos:"noun"},
  {k:"바닥",r:"badak",en:"floor/ground",pos:"noun"},
  {k:"천장",r:"cheonjang",en:"ceiling",pos:"noun"},
  {k:"창문",r:"changmun",en:"window",pos:"noun"},
  {k:"문",r:"mun",en:"door",pos:"noun"},
  {k:"소파",r:"sopa",en:"sofa/couch",pos:"noun"},
  {k:"침대",r:"chimdae",en:"bed",pos:"noun"},
  {k:"책상",r:"chaeksang",en:"desk",pos:"noun"},
  {k:"옷장",r:"otjang",en:"wardrobe/closet",pos:"noun"},
  {k:"서랍",r:"seorap",en:"drawer",pos:"noun"},
  {k:"거울",r:"geoul",en:"mirror",pos:"noun"},
  {k:"커튼",r:"keoteun",en:"curtain",pos:"noun"},
  {k:"카펫",r:"kapet",en:"carpet/rug",pos:"noun"},
  // TRANSPORT
  {k:"버스",r:"beoseu",en:"bus",pos:"noun"},
  {k:"택시",r:"taeksi",en:"taxi",pos:"noun"},
  {k:"기차",r:"gicha",en:"train",pos:"noun"},
  {k:"고속버스",r:"gosokbeoseu",en:"express bus",pos:"noun"},
  {k:"고속철도",r:"gosokcheirdo",en:"high-speed rail (KTX)",pos:"noun"},
  {k:"자동차",r:"jadongcha",en:"car/automobile",pos:"noun"},
  {k:"오토바이",r:"otobai",en:"motorcycle",pos:"noun"},
  {k:"배",r:"bae",en:"ship/boat",pos:"noun"},
  {k:"헬리콥터",r:"hellikopteo",en:"helicopter",pos:"noun"},
  {k:"도로",r:"doro",en:"road",pos:"noun"},
  {k:"거리",r:"geori",en:"street",pos:"noun"},
  {k:"골목",r:"golmok",en:"alley/lane",pos:"noun"},
  {k:"교차로",r:"gyocharo",en:"intersection",pos:"noun"},
  {k:"신호등",r:"sinhodeung",en:"traffic light",pos:"noun"},
  {k:"횡단보도",r:"hoengdanbodo",en:"crosswalk/pedestrian crossing",pos:"noun"},
  {k:"주차장",r:"juchajang",en:"parking lot",pos:"noun"},
  {k:"주유소",r:"juyuso",en:"gas station",pos:"noun"},
  {k:"정류장",r:"jeongyujang",en:"bus stop",pos:"noun"},
  {k:"역",r:"yeok",en:"station",pos:"noun"},
  {k:"출구",r:"chulgu",en:"exit",pos:"noun"},
  // ARTS VERBS
  {k:"그리다",r:"geurida",en:"to draw/paint",pos:"verb"},
  {k:"찍다",r:"jjikda",en:"to take a photo",pos:"verb"},
  {k:"노래하다",r:"noraehada",en:"to sing",pos:"verb"},
  {k:"연주하다",r:"yeonjuhada",en:"to play an instrument",pos:"verb"},
  {k:"춤추다",r:"chumchuda",en:"to dance",pos:"verb"},
  {k:"연기하다",r:"yeongihada",en:"to act",pos:"verb"},
  {k:"감상하다",r:"gamsanghada",en:"to appreciate art",pos:"verb"},
  {k:"창작하다",r:"changjakhada",en:"to create",pos:"verb"},
  {k:"전시하다",r:"jeonsihada",en:"to exhibit",pos:"verb"},
  {k:"감독하다",r:"gamdokhada",en:"to direct",pos:"verb"},
  // SPORTS VERBS
  {k:"뛰다",r:"ttwida",en:"to run/jump",pos:"verb"},
  {k:"치다",r:"chida",en:"to hit/strike",pos:"verb"},
  {k:"던지다",r:"deonjida",en:"to throw",pos:"verb"},
  {k:"잡다",r:"japda",en:"to catch/grab",pos:"verb"},
  {k:"차다",r:"chada",en:"to kick",pos:"verb"},
  {k:"수영하다",r:"suyeonghada",en:"to swim",pos:"verb"},
  {k:"이기다",r:"igida",en:"to win",pos:"verb"},
  {k:"지다",r:"jida",en:"to lose",pos:"verb"},
  {k:"응원하다",r:"eungwonhada",en:"to cheer for",pos:"verb"},
  {k:"연습하다",r:"yeonseuphada",en:"to practice",pos:"verb"},
  // TRANSPORT VERBS
  {k:"타다",r:"tada",en:"to ride/board",pos:"verb"},
  {k:"내리다",r:"naerida",en:"to get off",pos:"verb"},
  {k:"운전하다",r:"unjeonhada",en:"to drive",pos:"verb"},
  {k:"주차하다",r:"juchahada",en:"to park",pos:"verb"},
  {k:"갈아타다",r:"garatada",en:"to transfer/change",pos:"verb"},
  {k:"환승하다",r:"hwanseunghada",en:"to transfer (transit)",pos:"verb"},
  {k:"예매하다",r:"yemaehada",en:"to book a ticket",pos:"verb"},
  {k:"탑승하다",r:"tapseunghada",en:"to board (plane/train)",pos:"verb"},
  {k:"도착하다",r:"dochakhada",en:"to arrive",pos:"verb"},
  {k:"출발하다",r:"chulbalhada",en:"to depart",pos:"verb"},
  // HOME ADJECTIVES
  {k:"넓다",r:"neolda",en:"wide/spacious",pos:"adj"},
  {k:"좁다",r:"jopda",en:"narrow/cramped",pos:"adj"},
  {k:"조용하다",r:"joyonghada",en:"quiet",pos:"adj"},
  {k:"시끄럽다",r:"sikkeureopda",en:"noisy/loud",pos:"adj"},
  {k:"따뜻하다",r:"ttatteuthada",en:"warm",pos:"adj"},
  {k:"서늘하다",r:"seo-neulhada",en:"cool/refreshing",pos:"adj"},
  {k:"밝다",r:"bakda",en:"bright",pos:"adj"},
  {k:"어둡다",r:"eodupta",en:"dark",pos:"adj"},
  {k:"편하다",r:"pyeonhada",en:"comfortable",pos:"adj"},
  {k:"불편하다",r:"bulpyeonhada",en:"uncomfortable",pos:"adj"},
  // CULTURE
  {k:"전통",r:"jeontong",en:"tradition",pos:"noun"},
  {k:"명절",r:"myeongjeol",en:"traditional holiday",pos:"noun"},
  {k:"추석",r:"chuseok",en:"Chuseok (harvest festival)",pos:"noun"},
  {k:"설날",r:"seollal",en:"Lunar New Year",pos:"noun"},
  {k:"한복",r:"hanbok",en:"traditional Korean clothes",pos:"noun"},
  {k:"한옥",r:"hanok",en:"traditional Korean house",pos:"noun"},
  {k:"사물놀이",r:"samulnori",en:"Korean percussion quartet",pos:"noun"},
  {k:"판소리",r:"pansori",en:"Korean narrative singing",pos:"noun"},
  {k:"K-팝",r:"K-pop",en:"K-pop music",pos:"noun"},
  {k:"한류",r:"hallyu",en:"Korean Wave/hallyu",pos:"noun"},
];

var vocab5 = [
  // SHOPPING & COMMERCE
  {k:"쇼핑",r:"syoping",en:"shopping",pos:"noun"},
  {k:"가게",r:"gage",en:"store/shop",pos:"noun"},
  {k:"백화점",r:"baekhwajeom",en:"department store",pos:"noun"},
  {k:"편의점",r:"pyeonuijeom",en:"convenience store",pos:"noun"},
  {k:"마트",r:"mateu",en:"mart/supermarket",pos:"noun"},
  {k:"온라인 쇼핑",r:"ollaein syoping",en:"online shopping",pos:"noun"},
  {k:"할인",r:"harin",en:"discount",pos:"noun"},
  {k:"세일",r:"seil",en:"sale",pos:"noun"},
  {k:"환불",r:"hwanbul",en:"refund",pos:"noun"},
  {k:"교환",r:"gyohwan",en:"exchange/return",pos:"noun"},
  {k:"영업시간",r:"yeongeopsigan",en:"business hours",pos:"noun"},
  {k:"바코드",r:"bakodeu",en:"barcode",pos:"noun"},
  {k:"영수증",r:"yeongsujeung",en:"receipt",pos:"noun"},
  {k:"쿠폰",r:"kupon",en:"coupon",pos:"noun"},
  {k:"포인트",r:"pointeu",en:"points/rewards",pos:"noun"},
  {k:"원",r:"won",en:"Korean won (currency)",pos:"noun"},
  {k:"가격",r:"gagyeok",en:"price",pos:"noun"},
  {k:"정가",r:"jeongga",en:"regular price",pos:"noun"},
  {k:"특가",r:"teukga",en:"special price",pos:"noun"},
  // EMOTIONS
  {k:"감정",r:"gamjeong",en:"emotion/feeling",pos:"noun"},
  {k:"기쁨",r:"gippeum",en:"joy/happiness",pos:"noun"},
  {k:"슬픔",r:"seulpeum",en:"sadness",pos:"noun"},
  {k:"분노",r:"bunno",en:"anger",pos:"noun"},
  {k:"두려움",r:"duryeoum",en:"fear",pos:"noun"},
  {k:"놀라움",r:"nollaum",en:"surprise/amazement",pos:"noun"},
  {k:"걱정",r:"geokjeong",en:"worry/concern",pos:"noun"},
  {k:"후회",r:"huhoe",en:"regret",pos:"noun"},
  {k:"질투",r:"jiltu",en:"jealousy",pos:"noun"},
  {k:"설렘",r:"seollem",en:"excitement/flutter",pos:"noun"},
  {k:"그리움",r:"geurieum",en:"longing/missing someone",pos:"noun"},
  {k:"자신감",r:"jasigam",en:"self-confidence",pos:"noun"},
  {k:"불안",r:"buran",en:"anxiety/unease",pos:"noun"},
  {k:"스트레스",r:"seuteurehseu",en:"stress",pos:"noun"},
  {k:"우울",r:"uul",en:"depression/gloom",pos:"noun"},
  // DAILY LIFE
  {k:"일과",r:"ilgwa",en:"daily routine",pos:"noun"},
  {k:"습관",r:"seupgwan",en:"habit",pos:"noun"},
  {k:"취미",r:"chwimi",en:"hobby",pos:"noun"},
  {k:"관심",r:"gwansim",en:"interest",pos:"noun"},
  {k:"목표",r:"mokpyo",en:"goal/objective",pos:"noun"},
  {k:"꿈",r:"kkum",en:"dream",pos:"noun"},
  {k:"계획",r:"gyehoek",en:"plan",pos:"noun"},
  {k:"약속",r:"yaksok",en:"promise/appointment",pos:"noun"},
  {k:"생일",r:"saengil",en:"birthday",pos:"noun"},
  {k:"결혼",r:"gyeolhon",en:"marriage/wedding",pos:"noun"},
  {k:"이혼",r:"ihon",en:"divorce",pos:"noun"},
  {k:"선물",r:"seonmul",en:"gift/present",pos:"noun"},
  {k:"편지",r:"pyeonji",en:"letter",pos:"noun"},
  {k:"메시지",r:"mesiji",en:"message",pos:"noun"},
  {k:"전화",r:"jeonhwa",en:"phone call",pos:"noun"},
  {k:"운",r:"un",en:"luck/fortune",pos:"noun"},
  // TIME WORDS
  {k:"숫자",r:"sutja",en:"number/digit",pos:"noun"},
  {k:"날짜",r:"naljja",en:"date (calendar)",pos:"noun"},
  {k:"요일",r:"yoil",en:"day of the week",pos:"noun"},
  {k:"월",r:"wol",en:"month",pos:"noun"},
  {k:"년",r:"nyeon",en:"year",pos:"noun"},
  {k:"세기",r:"segi",en:"century",pos:"noun"},
  {k:"분",r:"bun",en:"minute",pos:"noun"},
  {k:"초",r:"cho",en:"second",pos:"noun"},
  {k:"주",r:"ju",en:"week",pos:"noun"},
  {k:"반",r:"ban",en:"half",pos:"noun"},
  // CONJUNCTIONS & GRAMMAR
  {k:"왜냐면",r:"waenyamyeon",en:"because (casual)",pos:"phrase"},
  {k:"그러므로",r:"geureomoero",en:"therefore/thus",pos:"phrase"},
  {k:"즉",r:"jeuk",en:"namely/that is",pos:"phrase"},
  {k:"따라서",r:"ttaraseo",en:"accordingly/therefore",pos:"phrase"},
  {k:"그러나",r:"geureona",en:"however/but",pos:"phrase"},
  {k:"반면에",r:"banmyeone",en:"on the other hand",pos:"phrase"},
  {k:"게다가",r:"gedaga",en:"furthermore/moreover",pos:"phrase"},
  {k:"결국",r:"gyeolguk",en:"in the end/eventually",pos:"phrase"},
  {k:"물론",r:"mullon",en:"of course/certainly",pos:"phrase"},
  {k:"사실",r:"sasil",en:"actually/in fact",pos:"noun"},
  // ADVANCED VERBS
  {k:"포기하다",r:"pogihada",en:"to give up",pos:"verb"},
  {k:"참다",r:"chamda",en:"to endure/hold back",pos:"verb"},
  {k:"속이다",r:"sogida",en:"to deceive/cheat",pos:"verb"},
  {k:"믿다",r:"mitda",en:"to believe/trust",pos:"verb"},
  {k:"의심하다",r:"euisimhada",en:"to doubt/suspect",pos:"verb"},
  {k:"허락하다",r:"heorakada",en:"to allow/permit",pos:"verb"},
  {k:"거절하다",r:"geojeorhada",en:"to refuse/reject",pos:"verb"},
  {k:"약속하다",r:"yaksokhada",en:"to promise",pos:"verb"},
  {k:"사과하다",r:"sagwahada",en:"to apologize",pos:"verb"},
  {k:"용서하다",r:"yongseohada",en:"to forgive",pos:"verb"},
  {k:"비교하다",r:"bigyohada",en:"to compare",pos:"verb"},
  {k:"판단하다",r:"pandanhada",en:"to judge",pos:"verb"},
  {k:"주장하다",r:"jujanghada",en:"to insist/claim",pos:"verb"},
  {k:"동의하다",r:"donguhada",en:"to agree",pos:"verb"},
  {k:"반대하다",r:"bandaehada",en:"to oppose",pos:"verb"},
  {k:"확인하다",r:"hwaginhada",en:"to confirm/check",pos:"verb"},
  {k:"준비하다",r:"junbihada",en:"to prepare",pos:"verb"},
  {k:"완성하다",r:"wanseonghada",en:"to complete/finish",pos:"verb"},
  {k:"실패하다",r:"silpaehada",en:"to fail",pos:"verb"},
  {k:"성공하다",r:"seonggonghada",en:"to succeed",pos:"verb"},
  // SHOPPING VERBS
  {k:"구매하다",r:"gumaehada",en:"to purchase",pos:"verb"},
  {k:"주문하다",r:"jumunhada",en:"to order (online/restaurant)",pos:"verb"},
  {k:"흥정하다",r:"heunggjeonghada",en:"to bargain/negotiate",pos:"verb"},
  {k:"지불하다",r:"jibulhada",en:"to pay",pos:"verb"},
  {k:"결제하다",r:"gyeoljehada",en:"to make payment",pos:"verb"},
  {k:"배송받다",r:"baesonbatda",en:"to receive delivery",pos:"verb"},
  {k:"교환하다",r:"gyohwanhada",en:"to exchange",pos:"verb"},
  {k:"환불받다",r:"hwanbul-batda",en:"to get a refund",pos:"verb"},
  {k:"할인받다",r:"harin-batda",en:"to get a discount",pos:"verb"},
  // ADJECTIVES
  {k:"솔직하다",r:"soljikada",en:"honest/frank",pos:"adj"},
  {k:"거짓되다",r:"geojitdoeda",en:"false/dishonest",pos:"adj"},
  {k:"진지하다",r:"jinjihada",en:"serious/earnest",pos:"adj"},
  {k:"가볍다",r:"gabyeopda",en:"light/trivial",pos:"adj"},
  {k:"철저하다",r:"cheoljeoahada",en:"thorough",pos:"adj"},
  {k:"부족하다",r:"bujokhada",en:"insufficient/lacking",pos:"adj"},
  {k:"충분하다",r:"chungbunhada",en:"sufficient/enough",pos:"adj"},
  {k:"적절하다",r:"jeokjeolhada",en:"appropriate/suitable",pos:"adj"},
  {k:"부적절하다",r:"bujeokjeolhada",en:"inappropriate",pos:"adj"},
  {k:"독특하다",r:"dokteukada",en:"unique/distinctive",pos:"adj"},
  // EMOTION VERBS
  {k:"느끼다",r:"neukkida",en:"to feel",pos:"verb"},
  {k:"표현하다",r:"pyohyeonhada",en:"to express",pos:"verb"},
  {k:"감동받다",r:"gamdong-batda",en:"to be moved/touched",pos:"verb"},
  {k:"위로하다",r:"wirohada",en:"to comfort/console",pos:"verb"},
  {k:"축하하다",r:"chukhahada",en:"to congratulate",pos:"verb"},
  {k:"진심으로",r:"jinsimeuro",en:"sincerely/from the heart",pos:"adv"},
  {k:"솔직히",r:"soljiki",en:"honestly/frankly",pos:"adv"},
  {k:"갑자기",r:"gapjagi",en:"suddenly",pos:"adv"},
  {k:"서서히",r:"seoseohi",en:"gradually/slowly",pos:"adv"},
  // DAILY PHRASES
  {k:"어서 오세요",r:"eoseo oseyo",en:"welcome (to a shop)",pos:"phrase"},
  {k:"뭐 드릴까요",r:"mwo deurilkkayo",en:"what can I get you?",pos:"phrase"},
  {k:"잠깐만요",r:"jamkkanmanyo",en:"just a moment please",pos:"phrase"},
  {k:"다음에 봐요",r:"daeume bwayo",en:"see you next time",pos:"phrase"},
  {k:"별일 없어요",r:"byeoril eopseoyo",en:"nothing special/all good",pos:"phrase"},
  {k:"조심하세요",r:"josimhaseyo",en:"be careful",pos:"phrase"},
  {k:"먼저 가세요",r:"meonjeo gaseyo",en:"after you/go ahead",pos:"phrase"},
  {k:"괜찮으시면",r:"gwaenchaneuisimyeon",en:"if it is okay with you",pos:"phrase"},
  {k:"잘 모르겠어요",r:"jal moreugeseoyo",en:"I am not sure",pos:"phrase"},
  {k:"그렇군요",r:"geureokkunyo",en:"I see/is that so",pos:"phrase"},
  // HOBBIES
  {k:"독서",r:"dokseo",en:"reading (books)",pos:"noun"},
  {k:"게임",r:"geim",en:"game/gaming",pos:"noun"},
  {k:"낚시",r:"naksi",en:"fishing",pos:"noun"},
  {k:"요가",r:"yoga",en:"yoga",pos:"noun"},
  {k:"명상",r:"myeongsang",en:"meditation",pos:"noun"},
  {k:"봉사",r:"bongsa",en:"volunteer work",pos:"noun"},
  {k:"캠핑",r:"kaemping",en:"camping",pos:"noun"},
  {k:"여가",r:"yeoga",en:"leisure time",pos:"noun"},
  {k:"산책",r:"sanchae",en:"stroll/walk",pos:"noun"},
  {k:"반려동물",r:"ballyeodongmul",en:"pet (companion animal)",pos:"noun"},
];

var vocab6 = [
  {k:"남편",r:"nampyeon",en:"husband",pos:"noun"},
  {k:"아내",r:"anae",en:"wife",pos:"noun"},
  {k:"아들",r:"adeul",en:"son",pos:"noun"},
  {k:"딸",r:"ttal",en:"daughter",pos:"noun"},
  {k:"형",r:"hyeong",en:"older brother (used by males)",pos:"noun"},
  {k:"언니",r:"eonni",en:"older sister (used by females)",pos:"noun"},
  {k:"오빠",r:"oppa",en:"older brother (used by females)",pos:"noun"},
  {k:"누나",r:"nuna",en:"older sister (used by males)",pos:"noun"},
  {k:"할머니",r:"halmeoni",en:"grandmother",pos:"noun"},
  {k:"할아버지",r:"harabeoji",en:"grandfather",pos:"noun"},
  {k:"이모",r:"imo",en:"aunt on mother side",pos:"noun"},
  {k:"삼촌",r:"samchon",en:"uncle",pos:"noun"},
  {k:"이웃",r:"iut",en:"neighbor",pos:"noun"},
  {k:"손님",r:"sonnim",en:"guest or customer",pos:"noun"},
  {k:"동료",r:"dongnyo",en:"colleague",pos:"noun"},
  {k:"머리",r:"meori",en:"head or hair",pos:"noun"},
  {k:"얼굴",r:"eolgul",en:"face",pos:"noun"},
  {k:"눈",r:"nun",en:"eye",pos:"noun"},
  {k:"코",r:"ko",en:"nose",pos:"noun"},
  {k:"입",r:"ip",en:"mouth",pos:"noun"},
  {k:"귀",r:"gwi",en:"ear",pos:"noun"},
  {k:"손",r:"son",en:"hand",pos:"noun"},
  {k:"발",r:"bal",en:"foot",pos:"noun"},
  {k:"다리",r:"dari",en:"leg",pos:"noun"},
  {k:"팔",r:"pal",en:"arm",pos:"noun"},
  {k:"배",r:"bae",en:"stomach",pos:"noun"},
  {k:"등",r:"deung",en:"back of body",pos:"noun"},
  {k:"어깨",r:"eokkae",en:"shoulder",pos:"noun"},
  {k:"목",r:"mok",en:"neck",pos:"noun"},
  {k:"가슴",r:"gaseum",en:"chest",pos:"noun"},
  {k:"밥",r:"bap",en:"cooked rice or meal",pos:"noun"},
  {k:"빵",r:"ppang",en:"bread",pos:"noun"},
  {k:"고기",r:"gogi",en:"meat",pos:"noun"},
  {k:"생선",r:"saengseon",en:"fish",pos:"noun"},
  {k:"채소",r:"chaeso",en:"vegetable",pos:"noun"},
  {k:"과일",r:"gwail",en:"fruit",pos:"noun"},
  {k:"우유",r:"uyu",en:"milk",pos:"noun"},
  {k:"커피",r:"keopi",en:"coffee",pos:"noun"},
  {k:"차",r:"cha",en:"tea",pos:"noun"},
  {k:"주스",r:"juseu",en:"juice",pos:"noun"},
  {k:"술",r:"sul",en:"alcohol",pos:"noun"},
  {k:"맥주",r:"maekju",en:"beer",pos:"noun"},
  {k:"소금",r:"sogeum",en:"salt",pos:"noun"},
  {k:"설탕",r:"seltang",en:"sugar",pos:"noun"},
  {k:"계란",r:"gyeran",en:"egg",pos:"noun"},
  {k:"집",r:"jip",en:"house or home",pos:"noun"},
  {k:"방",r:"bang",en:"room",pos:"noun"},
  {k:"부엌",r:"bueok",en:"kitchen",pos:"noun"},
  {k:"화장실",r:"hwajangsil",en:"bathroom",pos:"noun"},
  {k:"거실",r:"geosil",en:"living room",pos:"noun"},
  {k:"은행",r:"eunhaeng",en:"bank",pos:"noun"},
  {k:"식당",r:"sikdang",en:"restaurant",pos:"noun"},
  {k:"카페",r:"kape",en:"cafe",pos:"noun"},
  {k:"편의점",r:"pyeonuijeom",en:"convenience store",pos:"noun"},
  {k:"서점",r:"seojeom",en:"bookstore",pos:"noun"},
  {k:"도서관",r:"doseogwan",en:"library",pos:"noun"},
  {k:"공원",r:"gongwon",en:"park",pos:"noun"},
  {k:"산",r:"san",en:"mountain",pos:"noun"},
  {k:"강",r:"gang",en:"river",pos:"noun"},
  {k:"바다",r:"bada",en:"sea or ocean",pos:"noun"},
  {k:"버스",r:"beoseu",en:"bus",pos:"noun"},
  {k:"택시",r:"taeksi",en:"taxi",pos:"noun"},
  {k:"기차",r:"gicha",en:"train",pos:"noun"},
  {k:"자동차",r:"jadongcha",en:"car",pos:"noun"},
  {k:"자전거",r:"jajeongeo",en:"bicycle",pos:"noun"},
  {k:"길",r:"gil",en:"road or street",pos:"noun"},
  {k:"신호등",r:"sinhodeung",en:"traffic light",pos:"noun"},
  {k:"횡단보도",r:"hoengdanbodo",en:"crosswalk",pos:"noun"},
  {k:"주차장",r:"juchajang",en:"parking lot",pos:"noun"},
  {k:"오늘",r:"oneul",en:"today",pos:"noun"},
  {k:"어제",r:"eoje",en:"yesterday",pos:"noun"},
  {k:"내일",r:"naeil",en:"tomorrow",pos:"noun"},
  {k:"아침",r:"achim",en:"morning",pos:"noun"},
  {k:"점심",r:"jeomsim",en:"lunch or noon",pos:"noun"},
  {k:"저녁",r:"jeonyeok",en:"evening",pos:"noun"},
  {k:"밤",r:"bam",en:"night",pos:"noun"},
  {k:"주말",r:"jumal",en:"weekend",pos:"noun"},
  {k:"평일",r:"pyeongil",en:"weekday",pos:"noun"},
  {k:"올해",r:"olhae",en:"this year",pos:"noun"},
  {k:"작년",r:"jangnyeon",en:"last year",pos:"noun"},
  {k:"내년",r:"naenyeon",en:"next year",pos:"noun"},
  {k:"계절",r:"gyejeol",en:"season",pos:"noun"},
  {k:"봄",r:"bom",en:"spring",pos:"noun"},
  {k:"여름",r:"yeoreum",en:"summer",pos:"noun"},
  {k:"가을",r:"gaeul",en:"autumn or fall",pos:"noun"},
  {k:"겨울",r:"gyeoul",en:"winter",pos:"noun"},
  {k:"비",r:"bi",en:"rain",pos:"noun"},
  {k:"바람",r:"baram",en:"wind",pos:"noun"},
  {k:"구름",r:"gureum",en:"cloud",pos:"noun"},
  {k:"햇빛",r:"haetbit",en:"sunlight",pos:"noun"},
  {k:"안개",r:"angae",en:"fog",pos:"noun"},
  {k:"책",r:"chaek",en:"book",pos:"noun"},
  {k:"신문",r:"sinmun",en:"newspaper",pos:"noun"},
  {k:"가방",r:"gabang",en:"bag",pos:"noun"},
  {k:"지갑",r:"jigap",en:"wallet",pos:"noun"},
  {k:"열쇠",r:"yeolsoe",en:"key",pos:"noun"},
  {k:"시계",r:"sigye",en:"clock or watch",pos:"noun"},
  {k:"안경",r:"angyeong",en:"glasses",pos:"noun"},
  {k:"우산",r:"usan",en:"umbrella",pos:"noun"},
  {k:"휴대폰",r:"hyudaepon",en:"mobile phone",pos:"noun"},
  {k:"컴퓨터",r:"keompyuteo",en:"computer",pos:"noun"},
  {k:"텔레비전",r:"tellebijeon",en:"television",pos:"noun"},
  {k:"냉장고",r:"naengjanggo",en:"refrigerator",pos:"noun"},
  {k:"세탁기",r:"setakgi",en:"washing machine",pos:"noun"},
  {k:"의자",r:"uija",en:"chair",pos:"noun"},
  {k:"침대",r:"chimdae",en:"bed",pos:"noun"},
  {k:"옷",r:"ot",en:"clothes",pos:"noun"},
  {k:"바지",r:"baji",en:"pants",pos:"noun"},
  {k:"치마",r:"chima",en:"skirt",pos:"noun"},
  {k:"셔츠",r:"syeocheu",en:"shirt",pos:"noun"},
  {k:"코트",r:"koteu",en:"coat",pos:"noun"},
  {k:"신발",r:"sinbal",en:"shoes",pos:"noun"},
  {k:"모자",r:"moja",en:"hat or cap",pos:"noun"},
  {k:"장갑",r:"janggap",en:"gloves",pos:"noun"},
  {k:"목도리",r:"mokdori",en:"scarf",pos:"noun"},
  {k:"양말",r:"yangmal",en:"socks",pos:"noun"},
  {k:"가다",r:"gada",en:"to go",pos:"verb"},
  {k:"오다",r:"oda",en:"to come",pos:"verb"},
  {k:"달리다",r:"dallida",en:"to run",pos:"verb"},
  {k:"걷다",r:"geotda",en:"to walk",pos:"verb"},
  {k:"뛰다",r:"ttwida",en:"to jump",pos:"verb"},
  {k:"앉다",r:"anda",en:"to sit",pos:"verb"},
  {k:"서다",r:"seoda",en:"to stand",pos:"verb"},
  {k:"눕다",r:"nupda",en:"to lie down",pos:"verb"},
  {k:"올라가다",r:"ollagada",en:"to go up",pos:"verb"},
  {k:"내려가다",r:"naeryeogada",en:"to go down",pos:"verb"},
  {k:"들어가다",r:"deureogada",en:"to enter",pos:"verb"},
  {k:"나오다",r:"naoda",en:"to come out",pos:"verb"},
  {k:"건너다",r:"geonneoda",en:"to cross",pos:"verb"},
  {k:"돌아오다",r:"doraoda",en:"to return",pos:"verb"},
  {k:"떠나다",r:"tteonada",en:"to leave",pos:"verb"},
  {k:"말하다",r:"malhada",en:"to speak",pos:"verb"},
  {k:"묻다",r:"mutda",en:"to ask",pos:"verb"},
  {k:"대답하다",r:"daedaphada",en:"to answer",pos:"verb"},
  {k:"설명하다",r:"seolmyeonghada",en:"to explain",pos:"verb"},
  {k:"생각하다",r:"saenggakhada",en:"to think",pos:"verb"},
  {k:"알다",r:"alda",en:"to know",pos:"verb"},
  {k:"모르다",r:"moreuda",en:"to not know",pos:"verb"},
  {k:"배우다",r:"baeuda",en:"to learn",pos:"verb"},
  {k:"가르치다",r:"gareuchida",en:"to teach",pos:"verb"},
  {k:"이해하다",r:"ihaehada",en:"to understand",pos:"verb"},
  {k:"기억하다",r:"gieokhada",en:"to remember",pos:"verb"},
  {k:"잊다",r:"itda",en:"to forget",pos:"verb"},
  {k:"선택하다",r:"seontaekhada",en:"to choose",pos:"verb"},
  {k:"결정하다",r:"gyeoljeonghada",en:"to decide",pos:"verb"},
  {k:"계획하다",r:"gyehoekada",en:"to plan",pos:"verb"},
  {k:"일어나다",r:"ireonada",en:"to wake up",pos:"verb"},
  {k:"씻다",r:"ssitda",en:"to wash",pos:"verb"},
  {k:"입다",r:"ipda",en:"to wear",pos:"verb"},
  {k:"벗다",r:"beotda",en:"to take off clothes",pos:"verb"},
  {k:"열다",r:"yeolda",en:"to open",pos:"verb"},
  {k:"닫다",r:"datda",en:"to close",pos:"verb"},
  {k:"켜다",r:"kyeoda",en:"to turn on",pos:"verb"},
  {k:"끄다",r:"kkeuda",en:"to turn off",pos:"verb"},
  {k:"청소하다",r:"cheongsohada",en:"to clean",pos:"verb"},
  {k:"요리하다",r:"yorihada",en:"to cook",pos:"verb"},
  {k:"버리다",r:"beorida",en:"to throw away",pos:"verb"},
  {k:"찾다",r:"chatda",en:"to find",pos:"verb"},
  {k:"잃다",r:"ilta",en:"to lose",pos:"verb"},
  {k:"받다",r:"batda",en:"to receive",pos:"verb"},
  {k:"웃다",r:"utda",en:"to laugh or smile",pos:"verb"},
  {k:"울다",r:"ulda",en:"to cry",pos:"verb"},
  {k:"좋아하다",r:"joahada",en:"to like",pos:"verb"},
  {k:"싫어하다",r:"sireohada",en:"to dislike",pos:"verb"},
  {k:"사랑하다",r:"saranghada",en:"to love",pos:"verb"},
  {k:"걱정하다",r:"geokjeonghada",en:"to worry",pos:"verb"},
  {k:"화내다",r:"hwaenaeda",en:"to get angry",pos:"verb"},
  {k:"즐기다",r:"jeulgida",en:"to enjoy",pos:"verb"},
  {k:"돕다",r:"dopda",en:"to help",pos:"verb"},
  {k:"초대하다",r:"chodaehada",en:"to invite",pos:"verb"},
  {k:"예쁘다",r:"yeppeuda",en:"pretty or beautiful",pos:"adj"},
  {k:"잘생기다",r:"jalsaenggida",en:"handsome",pos:"adj"},
  {k:"어리다",r:"eorida",en:"young",pos:"adj"},
  {k:"늙다",r:"neukda",en:"old (person)",pos:"adj"},
  {k:"새롭다",r:"saeropda",en:"new",pos:"adj"},
  {k:"낡다",r:"nakda",en:"old (object)",pos:"adj"},
  {k:"깨끗하다",r:"kkaekkeuthada",en:"clean",pos:"adj"},
  {k:"더럽다",r:"deoropda",en:"dirty",pos:"adj"},
  {k:"가볍다",r:"gabyeopda",en:"light in weight",pos:"adj"},
  {k:"무겁다",r:"mugeobda",en:"heavy",pos:"adj"},
  {k:"슬프다",r:"seulpeuda",en:"sad",pos:"adj"},
  {k:"무섭다",r:"museopda",en:"scary",pos:"adj"},
  {k:"신나다",r:"sinnada",en:"excited",pos:"adj"},
  {k:"심심하다",r:"simsimhada",en:"bored",pos:"adj"},
  {k:"배고프다",r:"baegopeuda",en:"hungry",pos:"adj"},
  {k:"배부르다",r:"baebureuda",en:"full after eating",pos:"adj"},
  {k:"목마르다",r:"mongmareuda",en:"thirsty",pos:"adj"},
  {k:"아프다",r:"apeuda",en:"sick or painful",pos:"adj"},
  {k:"괜찮다",r:"gwaenchanta",en:"okay or fine",pos:"adj"},
  {k:"바쁘다",r:"bappeuda",en:"busy",pos:"adj"},
  {k:"길다",r:"gilda",en:"long",pos:"adj"},
  {k:"짧다",r:"jjalda",en:"short in length",pos:"adj"},
  {k:"넓다",r:"neolda",en:"wide or spacious",pos:"adj"},
  {k:"좁다",r:"jopda",en:"narrow",pos:"adj"},
  {k:"높다",r:"nopda",en:"high or tall",pos:"adj"},
  {k:"낮다",r:"natda",en:"low",pos:"adj"},
  {k:"많다",r:"manta",en:"many or much",pos:"adj"},
  {k:"적다",r:"jeokda",en:"few or little",pos:"adj"},
  {k:"같다",r:"gatda",en:"same or equal",pos:"adj"},
  {k:"다르다",r:"dareuda",en:"different",pos:"adj"},
  {k:"너무",r:"neomu",en:"too much or very",pos:"adv"},
  {k:"조금",r:"jogeum",en:"a little",pos:"adv"},
  {k:"많이",r:"mani",en:"a lot",pos:"adv"},
  {k:"아직",r:"ajik",en:"still or yet",pos:"adv"},
  {k:"이미",r:"imi",en:"already",pos:"adv"},
  {k:"곧",r:"got",en:"soon",pos:"adv"},
  {k:"자주",r:"jaju",en:"often",pos:"adv"},
  {k:"다시",r:"dasi",en:"again",pos:"adv"},
  {k:"천천히",r:"cheoncheonhi",en:"slowly",pos:"adv"},
  {k:"혼자",r:"honja",en:"alone",pos:"adv"},
  {k:"함께",r:"hamkke",en:"together",pos:"adv"},
  {k:"바로",r:"baro",en:"right away",pos:"adv"},
  {k:"특히",r:"teuki",en:"especially",pos:"adv"},
  {k:"보통",r:"botong",en:"usually",pos:"adv"},
  {k:"전혀",r:"jeonhyeo",en:"not at all",pos:"adv"},
  {k:"그래서",r:"geuraeseo",en:"so or therefore",pos:"phrase"},
  {k:"하지만",r:"hajiman",en:"but or however",pos:"phrase"},
  {k:"그리고",r:"geurigo",en:"and or also",pos:"phrase"},
  {k:"그런데",r:"geureonde",en:"by the way",pos:"phrase"},
  {k:"아니면",r:"animyeon",en:"or otherwise",pos:"phrase"},
  {k:"만약",r:"manyak",en:"if",pos:"phrase"},
  {k:"드디어",r:"deudieo",en:"finally",pos:"phrase"},
  {k:"갑자기",r:"gapjagi",en:"suddenly",pos:"phrase"},
  {k:"왜냐하면",r:"waenyahamyeon",en:"because",pos:"phrase"},
  {k:"비록",r:"birok",en:"although",pos:"phrase"},
];

var vocab7 = [
  {k:"가족",r:"gajok",en:"family",pos:"noun"},
  {k:"친구",r:"chingu",en:"friend",pos:"noun"},
  {k:"학교",r:"hakgyo",en:"school",pos:"noun"},
  {k:"선생님",r:"seonsaengnim",en:"teacher",pos:"noun"},
  {k:"음식",r:"eumsik",en:"food",pos:"noun"},
  {k:"물",r:"mul",en:"water",pos:"noun"},
  {k:"시간",r:"sigan",en:"time",pos:"noun"},
  {k:"날씨",r:"nalssi",en:"weather",pos:"noun"},
  {k:"여행",r:"yeohaeng",en:"travel",pos:"noun"},
  {k:"도시",r:"dosi",en:"city",pos:"noun"},
  {k:"나라",r:"nara",en:"country",pos:"noun"},
  {k:"언어",r:"eoneo",en:"language",pos:"noun"},
  {k:"회사",r:"hoesa",en:"company",pos:"noun"},
  {k:"병원",r:"byeongwon",en:"hospital",pos:"noun"},
  {k:"약국",r:"yakguk",en:"pharmacy",pos:"noun"},
  {k:"시장",r:"sijang",en:"market",pos:"noun"},
  {k:"지하철",r:"jihacheol",en:"subway",pos:"noun"},
  {k:"비행기",r:"bihaenggi",en:"airplane",pos:"noun"},
  {k:"공항",r:"gonghang",en:"airport",pos:"noun"},
  {k:"호텔",r:"hotel",en:"hotel",pos:"noun"},
  {k:"사다",r:"sada",en:"to buy",pos:"verb"},
  {k:"팔다",r:"palda",en:"to sell",pos:"verb"},
  {k:"읽다",r:"ikda",en:"to read",pos:"verb"},
  {k:"쓰다",r:"sseuda",en:"to write",pos:"verb"},
  {k:"듣다",r:"deutda",en:"to listen",pos:"verb"},
  {k:"보다",r:"boda",en:"to see",pos:"verb"},
  {k:"먹다",r:"meokda",en:"to eat",pos:"verb"},
  {k:"마시다",r:"masida",en:"to drink",pos:"verb"},
  {k:"자다",r:"jada",en:"to sleep",pos:"verb"},
  {k:"일하다",r:"ilhada",en:"to work",pos:"verb"},
  {k:"공부하다",r:"gongbuhada",en:"to study",pos:"verb"},
  {k:"여행하다",r:"yeohaenghada",en:"to travel",pos:"verb"},
  {k:"만나다",r:"mannada",en:"to meet",pos:"verb"},
  {k:"기다리다",r:"gidarida",en:"to wait",pos:"verb"},
  {k:"도착하다",r:"dochakhada",en:"to arrive",pos:"verb"},
  {k:"크다",r:"keuda",en:"big",pos:"adj"},
  {k:"작다",r:"jakda",en:"small",pos:"adj"},
  {k:"빠르다",r:"ppareuda",en:"fast",pos:"adj"},
  {k:"느리다",r:"neurida",en:"slow",pos:"adj"},
  {k:"비싸다",r:"bissada",en:"expensive",pos:"adj"},
  {k:"싸다",r:"ssada",en:"cheap",pos:"adj"},
  {k:"맛있다",r:"masitda",en:"delicious",pos:"adj"},
  {k:"피곤하다",r:"pigonhada",en:"tired",pos:"adj"},
  {k:"건강하다",r:"geonganghada",en:"healthy",pos:"adj"},
  {k:"행복하다",r:"haengbokhada",en:"happy",pos:"adj"},
  {k:"항상",r:"hangsang",en:"always",pos:"adverb"},
  {k:"가끔",r:"gakkeum",en:"sometimes",pos:"adverb"},
  {k:"빨리",r:"ppalli",en:"quickly",pos:"adverb"},
  {k:"같이",r:"gachi",en:"together",pos:"adverb"},
  {k:"정말",r:"jeongmal",en:"really",pos:"adverb"},
  {k:"안녕하세요",r:"annyeonghaseyo",en:"hello",pos:"phrase"},
  {k:"감사합니다",r:"gamsahamnida",en:"thank you",pos:"phrase"},
  {k:"죄송합니다",r:"joesonghamnida",en:"sorry",pos:"phrase"},
  {k:"괜찮아요",r:"gwaenchanayo",en:"okay",pos:"phrase"},
  {k:"네",r:"ne",en:"yes",pos:"phrase"},
  {k:"아니요",r:"aniyo",en:"no",pos:"phrase"},
  {k:"뭐",r:"mwo",en:"what",pos:"phrase"},
  {k:"어디",r:"eodi",en:"where",pos:"phrase"},
  {k:"언제",r:"eonje",en:"when",pos:"phrase"},
  {k:"왜",r:"wae",en:"why",pos:"phrase"},
  {k:"어떻게",r:"eotteoke",en:"how",pos:"phrase"},
  {k:"가다",r:"gada",en:"to go",pos:"verb"},
  {k:"오다",r:"oda",en:"to come",pos:"verb"},
  {k:"하다",r:"hada",en:"to do",pos:"verb"},
  {k:"있다",r:"itda",en:"to have/exist",pos:"verb"},
  {k:"없다",r:"eopda",en:"to not have",pos:"verb"},
  {k:"좋다",r:"jota",en:"good",pos:"adj"},
  {k:"싫다",r:"silta",en:"dislike",pos:"adj"},
  {k:"많다",r:"manta",en:"many",pos:"adj"},
  {k:"적다",r:"jeokda",en:"few",pos:"adj"},
  {k:"지금",r:"jigeum",en:"now",pos:"adverb"},
  {k:"오늘",r:"oneul",en:"today",pos:"adverb"},
  {k:"내일",r:"naeil",en:"tomorrow",pos:"adverb"},
  {k:"어제",r:"eoje",en:"yesterday",pos:"adverb"},
  {k:"집",r:"jip",en:"home",pos:"noun"},
  {k:"방",r:"bang",en:"room",pos:"noun"},
  {k:"문",r:"mun",en:"door",pos:"noun"},
  {k:"책",r:"chaek",en:"book",pos:"noun"},
  {k:"커피",r:"keopi",en:"coffee",pos:"noun"},
  {k:"차",r:"cha",en:"tea",pos:"noun"},
  {k:"밥",r:"bap",en:"rice",pos:"noun"},
  {k:"물건",r:"mulgeon",en:"item",pos:"noun"},
  {k:"주세요",r:"juseyo",en:"please give",pos:"phrase"},
  {k:"있어요",r:"isseoyo",en:"there is",pos:"phrase"},
  {k:"없어요",r:"eopseoyo",en:"there is not",pos:"phrase"},
  {k:"같아요",r:"gatayo",en:"seems like",pos:"phrase"},
  {k:"알아요",r:"arayo",en:"I know",pos:"phrase"},
  {k:"몰라요",r:"mollayo",en:"I don't know",pos:"phrase"},
  {k:"시작하다",r:"sijakada",en:"to start",pos:"verb"},
  {k:"끝나다",r:"kkeunnada",en:"to finish",pos:"verb"},
  {k:"열다",r:"yeolda",en:"to open",pos:"verb"},
  {k:"닫다",r:"datda",en:"to close",pos:"verb"},
  {k:"앉다",r:"anda",en:"to sit",pos:"verb"},
  {k:"서다",r:"seoda",en:"to stand",pos:"verb"},
  {k:"웃다",r:"utda",en:"to smile",pos:"verb"},
  {k:"울다",r:"ulda",en:"to cry",pos:"verb"},
  {k:"배우다",r:"baeuda",en:"to learn",pos:"verb"},
  {k:"가르치다",r:"gareuchida",en:"to teach",pos:"verb"},
];

var vocab8 = [
  {k:"회의실",r:"hoeuisil",en:"meeting room",pos:"noun"},
  {k:"프레젠테이션",r:"peurejenteisyeon",en:"presentation",pos:"noun"},
  {k:"프로젝트",r:"peurojekteu",en:"project",pos:"noun"},
  {k:"데드라인",r:"dedeullain",en:"deadline",pos:"noun"},
  {k:"업무",r:"eopmu",en:"work/task",pos:"noun"},
  {k:"스케줄",r:"seukeジュール",en:"schedule",pos:"noun"},
  {k:"아젠다",r:"ajenda",en:"agenda",pos:"noun"},
  {k:"피드백",r:"pidibaek",en:"feedback",pos:"noun"},
  {k:"성과",r:"seonggwa",en:"performance/result",pos:"noun"},
  {k:"목표",r:"mokpyo",en:"goal/target",pos:"noun"},
  {k:"고객",r:"gogaek",en:"customer/client",pos:"noun"},
  {k:"파트너",r:"pateoneo",en:"partner",pos:"noun"},
  {k:"계약서",r:"gyeyakseo",en:"contract",pos:"noun"},
  {k:"제안서",r:"jeanseo",en:"proposal",pos:"noun"},
  {k:"예산",r:"yesan",en:"budget",pos:"noun"},
  {k:"수익",r:"surik",en:"revenue/profit",pos:"noun"},
  {k:"비용",r:"biyong",en:"cost/expense",pos:"noun"},
  {k:"마케팅",r:"maketing",en:"marketing",pos:"noun"},
  {k:"판매",r:"panmae",en:"sales",pos:"noun"},
  {k:"협상하다",r:"hyeopsanghada",en:"to negotiate",pos:"verb"},
  {k:"제시하다",r:"jesihada",en:"to present/propose",pos:"verb"},
  {k:"승인하다",r:"seunginhada",en:"to approve",pos:"verb"},
  {k:"지연되다",r:"jiyeondoda",en:"to be delayed",pos:"verb"},
  {k:"해결하다",r:"haegyeolhada",en:"to solve",pos:"verb"},
  {k:"조정하다",r:"jojeonghada",en:"to adjust",pos:"verb"},
  // ... 25 more business terms
];

// 🔥 NEW SET 9: TRAVEL & TOURISM
var vocab9 = [
  {k:"여권",r:"yeogwon",en:"passport",pos:"noun"},
  {k:"비자",r:"bija",en:"visa",pos:"noun"},
  {k:"항공권",r:"hanggonggwon",en:"airplane ticket",pos:"noun"},
  {k:"호텔",r:"hotel",en:"hotel",pos:"noun"},
  {k:"관광지",r:"gwangwangji",en:"tourist attraction",pos:"noun"},
  {k:"기념품",r:"ginyeompum",en:"souvenir",pos:"noun"},
  {k:"여행사",r:"yeohangsa",en:"travel agency",pos:"noun"},
  {k:"가이드",r:"gaideu",en:"guide",pos:"noun"},
  {k:"짐",r:"jim",en:"luggage",pos:"noun"},
  {k:"탑승구",r:"tapseunggu",en:"gate",pos:"noun"},
  {k:"출국",r:"chulguk",en:"departure",pos:"noun"},
  {k:"입국",r:"ipguk",en:"arrival",pos:"noun"},
  {k:"환전소",r:"hwanjeonso",en:"money exchange",pos:"noun"},
  {k:"관광객",r:"gwangwanggaek",en:"tourist",pos:"noun"},
  {k:"랜드마크",r:"raendeumakeu",en:"landmark",pos:"noun"},
  {k:"예약하다",r:"yeyakhada",en:"to reserve",pos:"verb"},
  {k:"탐험하다",r:"tamheomhada",en:"to explore",pos:"verb"},
  {k:"방문하다",r:"bangmunhada",en:"to visit",pos:"verb"},
  {k:"촬영하다",r:"chwalyeonghada",en:"to take photos",pos:"verb"},
  {k:"휴식하다",r:"hyusikhada",en:"to rest",pos:"verb"},
  // ... 25 more travel terms
];

// 🔥 NEW SET 10: TECHNOLOGY & INTERNET
var vocab10 = [
  {k:"웹사이트",r:"weopsaiteu",en:"website",pos:"noun"},
  {k:"알고리즘",r:"algorijeum",en:"algorithm",pos:"noun"},
  {k:"클라우드",r:"keullaudeu",en:"cloud",pos:"noun"},
  {k:"보안",r:"boan",en:"security",pos:"noun"},
  {k:"암호",r:"amho",en:"password",pos:"noun"},
  {k:"해킹",r:"haeking",en:"hacking",pos:"noun"},
  {k:"버그",r:"beogeu",en:"bug",pos:"noun"},
  {k:"업데이트",r:"eopdeiteu",en:"update",pos:"noun"},
  {k:"플랫폼",r:"peullaetpom",en:"platform",pos:"noun"},
  {k:"스트리밍",r:"seuteuriming",en:"streaming",pos:"noun"},
  {k:"소셜미디어",r:"sosyeolmijia",en:"social media",pos:"noun"},
  {k:"해시태그",r:"haesitaeg",en:"hashtag",pos:"noun"},
  {k:"라이브",r:"raibeu",en:"live",pos:"noun"},
  {k:"가상현실",r:"gasanghyeonsil",en:"virtual reality",pos:"noun"},
  {k:"빅데이터",r:"bigdeiteo",en:"big data",pos:"noun"},
  {k:"코딩",r:"koding",en:"coding",pos:"noun"},
  {k:"프로그래밍",r:"peurogeuraemming",en:"programming",pos:"noun"},
  {k:"디버깅",r:"dibeogging",en:"debugging",pos:"noun"},
  {k:"설치하다",r:"seolchihada",en:"to install",pos:"verb"},
  {k:"접속하다",r:"jeopsokhada",en:"to connect/login",pos:"verb"},
  // ... 25 more tech terms
];

// 🔥 NEW SET 11: MEDICAL & HEALTH
var vocab11 = [
  {k:"증상",r:"jeungsang",en:"symptom",pos:"noun"},
  {k:"진단",r:"jindan",en:"diagnosis",pos:"noun"},
  {k:"치료",r:"chiryo",en:"treatment",pos:"noun"},
  {k:"면역력",r:"myeonyeokryeok",en:"immunity",pos:"noun"},
  {k:"영양소",r:"yeongyangsso",en:"nutrient",pos:"noun"},
  {k:"비타민",r:"bitamin",en:"vitamin",pos:"noun"},
  {k:"칼로리",r:"kallori",en:"calorie",pos:"noun"},
  {k:"다이어트",r:"daieoteu",en:"diet",pos:"noun"},
  {k:"재활",r:"jaehwal",en:"rehabilitation",pos:"noun"},
  {k:"응급실",r:"eunggeumsil",en:"emergency room",pos:"noun"},
  {k:"혈당",r:"hyeoltang",en:"blood sugar",pos:"noun"},
  {k:"콜레스테롤",r:"kolleseuteerol",en:"cholesterol",pos:"noun"},
  {k:"알레르기",r:"allereugi",en:"allergy",pos:"noun"},
  {k:"면역",r:"myeonyeok",en:"immune system",pos:"noun"},
  {k:"예방접종",r:"yebangjeopjong",en:"vaccination",pos:"noun"},
  {k:"수술",r:"susul",en:"surgery",pos:"noun"},
  {k:"마취",r:"machwi",en:"anesthesia",pos:"noun"},
  {k:"회복",r:"hoeboe",en:"recovery",pos:"noun"},
  {k:"처방전",r:"cheobangjeon",en:"prescription",pos:"noun"},
  {k:"부작용",r:"bujagyong",en:"side effect",pos:"noun"},
  // ... 25 more medical terms
];

// 🔥 NEW SET 12: ENVIRONMENT & ECOLOGY
var vocab12 = [
  {k:"기후변화",r:"gihubyeonhwa",en:"climate change",pos:"noun"},
  {k:"재생에너지",r:"jaesaengeoneoji",en:"renewable energy",pos:"noun"},
  {k:"플라스틱",r:"peullaseutik",en:"plastic",pos:"noun"},
  {k:"오염물질",r:"oyeommuljil",en:"pollutant",pos:"noun"},
  {k:"생물다양성",r:"saengmuldanyangseong",en:"biodiversity",pos:"noun"},
  {k:"탄소중립",r:"tansojungnip",en:"carbon neutral",pos:"noun"},
  {k:"미세먼지",r:"misemeonji",en:"fine dust",pos:"noun"},
  {k:"해양",r:"haeyang",en:"ocean",pos:"noun"},
  {k:"삼림",r:"sallim",en:"forest",pos:"noun"},
  {k:"보호구역",r:"bohoguyeok",en:"protected area",pos:"noun"},
  {k:"멸종위기",r:"myeoljongwigi",en:"endangered",pos:"noun"},
  {k:"지속가능",r:"jisugaunghagi",en:"sustainable",pos:"noun"},
  {k:"순환경제",r:"sunhwan-gyeongje",en:"circular economy",pos:"noun"},
  {k:"탄소배출",r:"tansobaechul",en:"carbon emission",pos:"noun"},
  {k:"생태계",r:"saengtaegye",en:"ecosystem",pos:"noun"},
  {k:"보호하다",r:"bohodada",en:"to protect",pos:"verb"},
  {k:"줄이다",r:"julida",en:"to reduce",pos:"verb"},
  {k:"재활용하다",r:"jaehwaryonghada",en:"to recycle",pos:"verb"},
  {k:"보존하다",r:"bojwanhada",en:"to preserve",pos:"verb"},
  {k:"위협받다",r:"wihyeombatda",en:"to be threatened",pos:"verb"},
  // ... 25 more environment terms
];

/* FIXED SET 6 - Removed duplicates */
var vocab6_fixed = [
  // Family & Relationships (no duplicates)
  {k:"남편",r:"nampyeon",en:"husband",pos:"noun"},
  {k:"아내",r:"anae",en:"wife",pos:"noun"},
  // Body parts
  {k:"머리",r:"meori",en:"head/hair",pos:"noun"},
  {k:"얼굴",r:"eolgul",en:"face",pos:"noun"},
  // ... complete fixed list without duplicates
];

/* 12 SET DEFINITIONS */
const SETS = [
  null,
  { id:1, name:'🍽️ Restaurant & Kitchen', vocab:vocab1, color:'#f0a050' },
  { id:2, name:'🔬 Nature & Science', vocab:vocab2, color:'#64ffda' },
  { id:3, name:'📚 Society, Work & Health', vocab:vocab3, color:'#7bb7ff' },
  { id:4, name:'🎨 Arts, Sports & Home', vocab:vocab4, color:'#e91e8c' },
  { id:5, name:'🛒 Shopping & Daily Life', vocab:vocab5, color:'#58a6ff' },
  { id:6, name:'🌟 Essential Words', vocab:vocab6_fixed, color:'#f0c060' },
  { id:7, name:'⭐ Beginner Essentials', vocab:vocab7, color:'#3ddba4' },
  // 🔥 NEW SETS
  { id:8, name:'💼 Business & Office', vocab:vocab8, color:'#ff6b6b' },
  { id:9, name:'✈️ Travel & Tourism', vocab:vocab9, color:'#4ecdc4' },
  { id:10,name:'💻 Technology', vocab:vocab10, color:'#45b7d1' },
  { id:11,name:'🏥 Medical & Health', vocab:vocab11, color:'#f9ca24' },
  { id:12,name:'🌍 Environment', vocab:vocab12, color:'#6c5ce7' },
];

const SET_META = [
  null,
  { emoji:'🍽️', name:'Restaurant & Kitchen', desc:'Food, cooking, restaurant terms', color:'#f0a050' },
  { emoji:'🔬', name:'Nature & Science', desc:'Nature, weather, technology', color:'#64ffda' },
  { emoji:'📚', name:'Society, Work & Health', desc:'Education, careers, medicine', color:'#7bb7ff' },
  { emoji:'🎨', name:'Arts, Sports & Home', desc:'Culture, sports, furniture', color:'#e91e8c' },
  { emoji:'🛒', name:'Shopping & Daily Life', desc:'Commerce, emotions, routines', color:'#58a6ff' },
  { emoji:'🌟', name:'Essential Words', desc:'Family, body, daily verbs', color:'#f0c060' },
  { emoji:'⭐', name:'Beginner Essentials', desc:'Core beginner vocabulary', color:'#3ddba4' },
  // 🔥 NEW
  { emoji:'💼', name:'Business & Office', desc:'Meetings, projects, business terms', color:'#ff6b6b' },
  { emoji:'✈️', name:'Travel & Tourism', desc:'Travel, hotels, sightseeing', color:'#4ecdc4' },
  { emoji:'💻', name:'Technology', desc:'Internet, apps, programming', color:'#45b7d1' },
  { emoji:'🏥', name:'Medical & Health', desc:'Health, medicine, nutrition', color:'#f9ca24' },
  { emoji:'🌍', name:'Environment', desc:'Ecology, climate, sustainability', color:'#6c5ce7' },
];